/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Groups.proto */

#ifndef PROTOBUF_C_Groups_2eproto__INCLUDED
#define PROTOBUF_C_Groups_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _AvatarUploadAttributes AvatarUploadAttributes;
typedef struct _Member Member;
typedef struct _PendingMember PendingMember;
typedef struct _RequestingMember RequestingMember;
typedef struct _AccessControl AccessControl;
typedef struct _Group Group;
typedef struct _GroupChange GroupChange;
typedef struct _GroupChange__Actions GroupChange__Actions;
typedef struct _GroupChange__Actions__AddMemberAction GroupChange__Actions__AddMemberAction;
typedef struct _GroupChange__Actions__DeleteMemberAction GroupChange__Actions__DeleteMemberAction;
typedef struct _GroupChange__Actions__ModifyMemberRoleAction GroupChange__Actions__ModifyMemberRoleAction;
typedef struct _GroupChange__Actions__ModifyMemberProfileKeyAction GroupChange__Actions__ModifyMemberProfileKeyAction;
typedef struct _GroupChange__Actions__AddPendingMemberAction GroupChange__Actions__AddPendingMemberAction;
typedef struct _GroupChange__Actions__DeletePendingMemberAction GroupChange__Actions__DeletePendingMemberAction;
typedef struct _GroupChange__Actions__PromotePendingMemberAction GroupChange__Actions__PromotePendingMemberAction;
typedef struct _GroupChange__Actions__AddRequestingMemberAction GroupChange__Actions__AddRequestingMemberAction;
typedef struct _GroupChange__Actions__DeleteRequestingMemberAction GroupChange__Actions__DeleteRequestingMemberAction;
typedef struct _GroupChange__Actions__PromoteRequestingMemberAction GroupChange__Actions__PromoteRequestingMemberAction;
typedef struct _GroupChange__Actions__ModifyTitleAction GroupChange__Actions__ModifyTitleAction;
typedef struct _GroupChange__Actions__ModifyDescriptionAction GroupChange__Actions__ModifyDescriptionAction;
typedef struct _GroupChange__Actions__ModifyAvatarAction GroupChange__Actions__ModifyAvatarAction;
typedef struct _GroupChange__Actions__ModifyDisappearingMessagesTimerAction GroupChange__Actions__ModifyDisappearingMessagesTimerAction;
typedef struct _GroupChange__Actions__ModifyAttributesAccessControlAction GroupChange__Actions__ModifyAttributesAccessControlAction;
typedef struct _GroupChange__Actions__ModifyMembersAccessControlAction GroupChange__Actions__ModifyMembersAccessControlAction;
typedef struct _GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction;
typedef struct _GroupChange__Actions__ModifyInviteLinkPasswordAction GroupChange__Actions__ModifyInviteLinkPasswordAction;
typedef struct _GroupChange__Actions__ModifyAnnouncementsOnlyAction GroupChange__Actions__ModifyAnnouncementsOnlyAction;
typedef struct _GroupChanges GroupChanges;
typedef struct _GroupChanges__GroupChangeState GroupChanges__GroupChangeState;
typedef struct _GroupAttributeBlob GroupAttributeBlob;
typedef struct _GroupInviteLink GroupInviteLink;
typedef struct _GroupInviteLink__GroupInviteLinkContentsV1 GroupInviteLink__GroupInviteLinkContentsV1;
typedef struct _GroupInviteLink__GroupInviteLinkContentsV10 GroupInviteLink__GroupInviteLinkContentsV10;
typedef struct _GroupJoinInfo GroupJoinInfo;
typedef struct _GroupExternalCredential GroupExternalCredential;


/* --- enums --- */

typedef enum _Member__Role {
  MEMBER__ROLE__UNKNOWN = 0,
  MEMBER__ROLE__DEFAULT = 1,
  MEMBER__ROLE__ADMINISTRATOR = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MEMBER__ROLE)
} Member__Role;
typedef enum _AccessControl__AccessRequired {
  ACCESS_CONTROL__ACCESS_REQUIRED__UNKNOWN = 0,
  ACCESS_CONTROL__ACCESS_REQUIRED__ANY = 1,
  ACCESS_CONTROL__ACCESS_REQUIRED__MEMBER = 2,
  ACCESS_CONTROL__ACCESS_REQUIRED__ADMINISTRATOR = 3,
  ACCESS_CONTROL__ACCESS_REQUIRED__UNSATISFIABLE = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ACCESS_CONTROL__ACCESS_REQUIRED)
} AccessControl__AccessRequired;

/* --- messages --- */

struct  _AvatarUploadAttributes
{
  ProtobufCMessage base;
  char *key;
  char *credential;
  char *acl;
  char *algorithm;
  char *date;
  char *policy;
  char *signature;
};
#define AVATAR_UPLOAD_ATTRIBUTES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&avatar_upload_attributes__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Member
{
  ProtobufCMessage base;
  ProtobufCBinaryData userid;
  Member__Role role;
  ProtobufCBinaryData profilekey;
  ProtobufCBinaryData presentation;
  uint32_t joinedatrevision;
};
#define MEMBER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&member__descriptor) \
    , {0,NULL}, MEMBER__ROLE__UNKNOWN, {0,NULL}, {0,NULL}, 0 }


struct  _PendingMember
{
  ProtobufCMessage base;
  Member *member;
  ProtobufCBinaryData addedbyuserid;
  uint64_t timestamp;
};
#define PENDING_MEMBER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pending_member__descriptor) \
    , NULL, {0,NULL}, 0 }


struct  _RequestingMember
{
  ProtobufCMessage base;
  ProtobufCBinaryData userid;
  ProtobufCBinaryData profilekey;
  ProtobufCBinaryData presentation;
  uint64_t timestamp;
};
#define REQUESTING_MEMBER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requesting_member__descriptor) \
    , {0,NULL}, {0,NULL}, {0,NULL}, 0 }


struct  _AccessControl
{
  ProtobufCMessage base;
  AccessControl__AccessRequired attributes;
  AccessControl__AccessRequired members;
  AccessControl__AccessRequired addfrominvitelink;
};
#define ACCESS_CONTROL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&access_control__descriptor) \
    , ACCESS_CONTROL__ACCESS_REQUIRED__UNKNOWN, ACCESS_CONTROL__ACCESS_REQUIRED__UNKNOWN, ACCESS_CONTROL__ACCESS_REQUIRED__UNKNOWN }


struct  _Group
{
  ProtobufCMessage base;
  ProtobufCBinaryData publickey;
  ProtobufCBinaryData title;
  char *avatar;
  ProtobufCBinaryData disappearingmessagestimer;
  AccessControl *accesscontrol;
  uint32_t revision;
  size_t n_members;
  Member **members;
  size_t n_pendingmembers;
  PendingMember **pendingmembers;
  size_t n_requestingmembers;
  RequestingMember **requestingmembers;
  ProtobufCBinaryData invitelinkpassword;
  ProtobufCBinaryData description;
  protobuf_c_boolean announcementsonly;
};
#define GROUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group__descriptor) \
    , {0,NULL}, {0,NULL}, (char *)protobuf_c_empty_string, {0,NULL}, NULL, 0, 0,NULL, 0,NULL, 0,NULL, {0,NULL}, {0,NULL}, 0 }


struct  _GroupChange__Actions__AddMemberAction
{
  ProtobufCMessage base;
  Member *added;
  protobuf_c_boolean joinfrominvitelink;
};
#define GROUP_CHANGE__ACTIONS__ADD_MEMBER_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__add_member_action__descriptor) \
    , NULL, 0 }


struct  _GroupChange__Actions__DeleteMemberAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData deleteduserid;
};
#define GROUP_CHANGE__ACTIONS__DELETE_MEMBER_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__delete_member_action__descriptor) \
    , {0,NULL} }


struct  _GroupChange__Actions__ModifyMemberRoleAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData userid;
  Member__Role role;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_MEMBER_ROLE_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_member_role_action__descriptor) \
    , {0,NULL}, MEMBER__ROLE__UNKNOWN }


struct  _GroupChange__Actions__ModifyMemberProfileKeyAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData presentation;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_MEMBER_PROFILE_KEY_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_member_profile_key_action__descriptor) \
    , {0,NULL} }


struct  _GroupChange__Actions__AddPendingMemberAction
{
  ProtobufCMessage base;
  PendingMember *added;
};
#define GROUP_CHANGE__ACTIONS__ADD_PENDING_MEMBER_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__add_pending_member_action__descriptor) \
    , NULL }


struct  _GroupChange__Actions__DeletePendingMemberAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData deleteduserid;
};
#define GROUP_CHANGE__ACTIONS__DELETE_PENDING_MEMBER_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__delete_pending_member_action__descriptor) \
    , {0,NULL} }


struct  _GroupChange__Actions__PromotePendingMemberAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData presentation;
};
#define GROUP_CHANGE__ACTIONS__PROMOTE_PENDING_MEMBER_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__promote_pending_member_action__descriptor) \
    , {0,NULL} }


struct  _GroupChange__Actions__AddRequestingMemberAction
{
  ProtobufCMessage base;
  RequestingMember *added;
};
#define GROUP_CHANGE__ACTIONS__ADD_REQUESTING_MEMBER_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__add_requesting_member_action__descriptor) \
    , NULL }


struct  _GroupChange__Actions__DeleteRequestingMemberAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData deleteduserid;
};
#define GROUP_CHANGE__ACTIONS__DELETE_REQUESTING_MEMBER_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__delete_requesting_member_action__descriptor) \
    , {0,NULL} }


struct  _GroupChange__Actions__PromoteRequestingMemberAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData userid;
  Member__Role role;
};
#define GROUP_CHANGE__ACTIONS__PROMOTE_REQUESTING_MEMBER_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__promote_requesting_member_action__descriptor) \
    , {0,NULL}, MEMBER__ROLE__UNKNOWN }


struct  _GroupChange__Actions__ModifyTitleAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData title;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_TITLE_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_title_action__descriptor) \
    , {0,NULL} }


struct  _GroupChange__Actions__ModifyDescriptionAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData description;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_DESCRIPTION_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_description_action__descriptor) \
    , {0,NULL} }


struct  _GroupChange__Actions__ModifyAvatarAction
{
  ProtobufCMessage base;
  char *avatar;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_AVATAR_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_avatar_action__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _GroupChange__Actions__ModifyDisappearingMessagesTimerAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData timer;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_DISAPPEARING_MESSAGES_TIMER_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_disappearing_messages_timer_action__descriptor) \
    , {0,NULL} }


struct  _GroupChange__Actions__ModifyAttributesAccessControlAction
{
  ProtobufCMessage base;
  AccessControl__AccessRequired attributesaccess;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_ATTRIBUTES_ACCESS_CONTROL_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_attributes_access_control_action__descriptor) \
    , ACCESS_CONTROL__ACCESS_REQUIRED__UNKNOWN }


struct  _GroupChange__Actions__ModifyMembersAccessControlAction
{
  ProtobufCMessage base;
  AccessControl__AccessRequired membersaccess;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_MEMBERS_ACCESS_CONTROL_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_members_access_control_action__descriptor) \
    , ACCESS_CONTROL__ACCESS_REQUIRED__UNKNOWN }


struct  _GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction
{
  ProtobufCMessage base;
  AccessControl__AccessRequired addfrominvitelinkaccess;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_ADD_FROM_INVITE_LINK_ACCESS_CONTROL_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_add_from_invite_link_access_control_action__descriptor) \
    , ACCESS_CONTROL__ACCESS_REQUIRED__UNKNOWN }


struct  _GroupChange__Actions__ModifyInviteLinkPasswordAction
{
  ProtobufCMessage base;
  ProtobufCBinaryData invitelinkpassword;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_INVITE_LINK_PASSWORD_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_invite_link_password_action__descriptor) \
    , {0,NULL} }


struct  _GroupChange__Actions__ModifyAnnouncementsOnlyAction
{
  ProtobufCMessage base;
  protobuf_c_boolean announcementsonly;
};
#define GROUP_CHANGE__ACTIONS__MODIFY_ANNOUNCEMENTS_ONLY_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__modify_announcements_only_action__descriptor) \
    , 0 }


struct  _GroupChange__Actions
{
  ProtobufCMessage base;
  ProtobufCBinaryData sourceuuid;
  uint32_t revision;
  size_t n_addmembers;
  GroupChange__Actions__AddMemberAction **addmembers;
  size_t n_deletemembers;
  GroupChange__Actions__DeleteMemberAction **deletemembers;
  size_t n_modifymemberroles;
  GroupChange__Actions__ModifyMemberRoleAction **modifymemberroles;
  size_t n_modifymemberprofilekeys;
  GroupChange__Actions__ModifyMemberProfileKeyAction **modifymemberprofilekeys;
  size_t n_addpendingmembers;
  GroupChange__Actions__AddPendingMemberAction **addpendingmembers;
  size_t n_deletependingmembers;
  GroupChange__Actions__DeletePendingMemberAction **deletependingmembers;
  size_t n_promotependingmembers;
  GroupChange__Actions__PromotePendingMemberAction **promotependingmembers;
  GroupChange__Actions__ModifyTitleAction *modifytitle;
  GroupChange__Actions__ModifyAvatarAction *modifyavatar;
  GroupChange__Actions__ModifyDisappearingMessagesTimerAction *modifydisappearingmessagestimer;
  GroupChange__Actions__ModifyAttributesAccessControlAction *modifyattributesaccess;
  GroupChange__Actions__ModifyMembersAccessControlAction *modifymemberaccess;
  GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction *modifyaddfrominvitelinkaccess;
  size_t n_addrequestingmembers;
  GroupChange__Actions__AddRequestingMemberAction **addrequestingmembers;
  size_t n_deleterequestingmembers;
  GroupChange__Actions__DeleteRequestingMemberAction **deleterequestingmembers;
  size_t n_promoterequestingmembers;
  GroupChange__Actions__PromoteRequestingMemberAction **promoterequestingmembers;
  GroupChange__Actions__ModifyInviteLinkPasswordAction *modifyinvitelinkpassword;
  GroupChange__Actions__ModifyDescriptionAction *modifydescription;
  GroupChange__Actions__ModifyAnnouncementsOnlyAction *modifyannouncementsonly;
};
#define GROUP_CHANGE__ACTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__actions__descriptor) \
    , {0,NULL}, 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0,NULL, 0,NULL, 0,NULL, NULL, NULL, NULL }


struct  _GroupChange
{
  ProtobufCMessage base;
  ProtobufCBinaryData actions;
  ProtobufCBinaryData serversignature;
  uint32_t changeepoch;
};
#define GROUP_CHANGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_change__descriptor) \
    , {0,NULL}, {0,NULL}, 0 }


struct  _GroupChanges__GroupChangeState
{
  ProtobufCMessage base;
  GroupChange *groupchange;
  Group *groupstate;
};
#define GROUP_CHANGES__GROUP_CHANGE_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_changes__group_change_state__descriptor) \
    , NULL, NULL }


struct  _GroupChanges
{
  ProtobufCMessage base;
  size_t n_groupchanges;
  GroupChanges__GroupChangeState **groupchanges;
};
#define GROUP_CHANGES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_changes__descriptor) \
    , 0,NULL }


typedef enum {
  GROUP_ATTRIBUTE_BLOB__CONTENT__NOT_SET = 0,
  GROUP_ATTRIBUTE_BLOB__CONTENT_TITLE = 1,
  GROUP_ATTRIBUTE_BLOB__CONTENT_AVATAR = 2,
  GROUP_ATTRIBUTE_BLOB__CONTENT_DISAPPEARING_MESSAGES_DURATION = 3,
  GROUP_ATTRIBUTE_BLOB__CONTENT_DESCRIPTION = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GROUP_ATTRIBUTE_BLOB__CONTENT)
} GroupAttributeBlob__ContentCase;

struct  _GroupAttributeBlob
{
  ProtobufCMessage base;
  GroupAttributeBlob__ContentCase content_case;
  union {
    char *title;
    ProtobufCBinaryData avatar;
    uint32_t disappearingmessagesduration;
    char *description;
  };
};
#define GROUP_ATTRIBUTE_BLOB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_attribute_blob__descriptor) \
    , GROUP_ATTRIBUTE_BLOB__CONTENT__NOT_SET, {0} }


struct  _GroupInviteLink__GroupInviteLinkContentsV1
{
  ProtobufCMessage base;
  ProtobufCBinaryData groupmasterkey;
  ProtobufCBinaryData invitelinkpassword;
};
#define GROUP_INVITE_LINK__GROUP_INVITE_LINK_CONTENTS_V1__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_invite_link__group_invite_link_contents_v1__descriptor) \
    , {0,NULL}, {0,NULL} }


/*
 *AA+ for ufsrv. Incorporate fid
 */
struct  _GroupInviteLink__GroupInviteLinkContentsV10
{
  ProtobufCMessage base;
  ProtobufCBinaryData groupmasterkey;
  ProtobufCBinaryData invitelinkpassword;
  uint64_t fid;
};
#define GROUP_INVITE_LINK__GROUP_INVITE_LINK_CONTENTS_V10__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_invite_link__group_invite_link_contents_v10__descriptor) \
    , {0,NULL}, {0,NULL}, 0 }


typedef enum {
  GROUP_INVITE_LINK__CONTENTS__NOT_SET = 0,
  GROUP_INVITE_LINK__CONTENTS_V1_CONTENTS = 1,
  GROUP_INVITE_LINK__CONTENTS_V10_CONTENTS = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GROUP_INVITE_LINK__CONTENTS)
} GroupInviteLink__ContentsCase;

struct  _GroupInviteLink
{
  ProtobufCMessage base;
  GroupInviteLink__ContentsCase contents_case;
  union {
    GroupInviteLink__GroupInviteLinkContentsV1 *v1contents;
    /*
     *AA+
     */
    GroupInviteLink__GroupInviteLinkContentsV10 *v10contents;
  };
};
#define GROUP_INVITE_LINK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_invite_link__descriptor) \
    , GROUP_INVITE_LINK__CONTENTS__NOT_SET, {0} }


struct  _GroupJoinInfo
{
  ProtobufCMessage base;
  ProtobufCBinaryData publickey;
  ProtobufCBinaryData title;
  char *avatar;
  uint32_t membercount;
  AccessControl__AccessRequired addfrominvitelink;
  uint32_t revision;
  protobuf_c_boolean pendingadminapproval;
  ProtobufCBinaryData description;
};
#define GROUP_JOIN_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_join_info__descriptor) \
    , {0,NULL}, {0,NULL}, (char *)protobuf_c_empty_string, 0, ACCESS_CONTROL__ACCESS_REQUIRED__UNKNOWN, 0, 0, {0,NULL} }


struct  _GroupExternalCredential
{
  ProtobufCMessage base;
  char *token;
};
#define GROUP_EXTERNAL_CREDENTIAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&group_external_credential__descriptor) \
    , (char *)protobuf_c_empty_string }


/* AvatarUploadAttributes methods */
void   avatar_upload_attributes__init
                     (AvatarUploadAttributes         *message);
size_t avatar_upload_attributes__get_packed_size
                     (const AvatarUploadAttributes   *message);
size_t avatar_upload_attributes__pack
                     (const AvatarUploadAttributes   *message,
                      uint8_t             *out);
size_t avatar_upload_attributes__pack_to_buffer
                     (const AvatarUploadAttributes   *message,
                      ProtobufCBuffer     *buffer);
AvatarUploadAttributes *
       avatar_upload_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   avatar_upload_attributes__free_unpacked
                     (AvatarUploadAttributes *message,
                      ProtobufCAllocator *allocator);
/* Member methods */
void   member__init
                     (Member         *message);
size_t member__get_packed_size
                     (const Member   *message);
size_t member__pack
                     (const Member   *message,
                      uint8_t             *out);
size_t member__pack_to_buffer
                     (const Member   *message,
                      ProtobufCBuffer     *buffer);
Member *
       member__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   member__free_unpacked
                     (Member *message,
                      ProtobufCAllocator *allocator);
/* PendingMember methods */
void   pending_member__init
                     (PendingMember         *message);
size_t pending_member__get_packed_size
                     (const PendingMember   *message);
size_t pending_member__pack
                     (const PendingMember   *message,
                      uint8_t             *out);
size_t pending_member__pack_to_buffer
                     (const PendingMember   *message,
                      ProtobufCBuffer     *buffer);
PendingMember *
       pending_member__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pending_member__free_unpacked
                     (PendingMember *message,
                      ProtobufCAllocator *allocator);
/* RequestingMember methods */
void   requesting_member__init
                     (RequestingMember         *message);
size_t requesting_member__get_packed_size
                     (const RequestingMember   *message);
size_t requesting_member__pack
                     (const RequestingMember   *message,
                      uint8_t             *out);
size_t requesting_member__pack_to_buffer
                     (const RequestingMember   *message,
                      ProtobufCBuffer     *buffer);
RequestingMember *
       requesting_member__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requesting_member__free_unpacked
                     (RequestingMember *message,
                      ProtobufCAllocator *allocator);
/* AccessControl methods */
void   access_control__init
                     (AccessControl         *message);
size_t access_control__get_packed_size
                     (const AccessControl   *message);
size_t access_control__pack
                     (const AccessControl   *message,
                      uint8_t             *out);
size_t access_control__pack_to_buffer
                     (const AccessControl   *message,
                      ProtobufCBuffer     *buffer);
AccessControl *
       access_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   access_control__free_unpacked
                     (AccessControl *message,
                      ProtobufCAllocator *allocator);
/* Group methods */
void   group__init
                     (Group         *message);
size_t group__get_packed_size
                     (const Group   *message);
size_t group__pack
                     (const Group   *message,
                      uint8_t             *out);
size_t group__pack_to_buffer
                     (const Group   *message,
                      ProtobufCBuffer     *buffer);
Group *
       group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   group__free_unpacked
                     (Group *message,
                      ProtobufCAllocator *allocator);
/* GroupChange__Actions__AddMemberAction methods */
void   group_change__actions__add_member_action__init
                     (GroupChange__Actions__AddMemberAction         *message);
/* GroupChange__Actions__DeleteMemberAction methods */
void   group_change__actions__delete_member_action__init
                     (GroupChange__Actions__DeleteMemberAction         *message);
/* GroupChange__Actions__ModifyMemberRoleAction methods */
void   group_change__actions__modify_member_role_action__init
                     (GroupChange__Actions__ModifyMemberRoleAction         *message);
/* GroupChange__Actions__ModifyMemberProfileKeyAction methods */
void   group_change__actions__modify_member_profile_key_action__init
                     (GroupChange__Actions__ModifyMemberProfileKeyAction         *message);
/* GroupChange__Actions__AddPendingMemberAction methods */
void   group_change__actions__add_pending_member_action__init
                     (GroupChange__Actions__AddPendingMemberAction         *message);
/* GroupChange__Actions__DeletePendingMemberAction methods */
void   group_change__actions__delete_pending_member_action__init
                     (GroupChange__Actions__DeletePendingMemberAction         *message);
/* GroupChange__Actions__PromotePendingMemberAction methods */
void   group_change__actions__promote_pending_member_action__init
                     (GroupChange__Actions__PromotePendingMemberAction         *message);
/* GroupChange__Actions__AddRequestingMemberAction methods */
void   group_change__actions__add_requesting_member_action__init
                     (GroupChange__Actions__AddRequestingMemberAction         *message);
/* GroupChange__Actions__DeleteRequestingMemberAction methods */
void   group_change__actions__delete_requesting_member_action__init
                     (GroupChange__Actions__DeleteRequestingMemberAction         *message);
/* GroupChange__Actions__PromoteRequestingMemberAction methods */
void   group_change__actions__promote_requesting_member_action__init
                     (GroupChange__Actions__PromoteRequestingMemberAction         *message);
/* GroupChange__Actions__ModifyTitleAction methods */
void   group_change__actions__modify_title_action__init
                     (GroupChange__Actions__ModifyTitleAction         *message);
/* GroupChange__Actions__ModifyDescriptionAction methods */
void   group_change__actions__modify_description_action__init
                     (GroupChange__Actions__ModifyDescriptionAction         *message);
/* GroupChange__Actions__ModifyAvatarAction methods */
void   group_change__actions__modify_avatar_action__init
                     (GroupChange__Actions__ModifyAvatarAction         *message);
/* GroupChange__Actions__ModifyDisappearingMessagesTimerAction methods */
void   group_change__actions__modify_disappearing_messages_timer_action__init
                     (GroupChange__Actions__ModifyDisappearingMessagesTimerAction         *message);
/* GroupChange__Actions__ModifyAttributesAccessControlAction methods */
void   group_change__actions__modify_attributes_access_control_action__init
                     (GroupChange__Actions__ModifyAttributesAccessControlAction         *message);
/* GroupChange__Actions__ModifyMembersAccessControlAction methods */
void   group_change__actions__modify_members_access_control_action__init
                     (GroupChange__Actions__ModifyMembersAccessControlAction         *message);
/* GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction methods */
void   group_change__actions__modify_add_from_invite_link_access_control_action__init
                     (GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction         *message);
/* GroupChange__Actions__ModifyInviteLinkPasswordAction methods */
void   group_change__actions__modify_invite_link_password_action__init
                     (GroupChange__Actions__ModifyInviteLinkPasswordAction         *message);
/* GroupChange__Actions__ModifyAnnouncementsOnlyAction methods */
void   group_change__actions__modify_announcements_only_action__init
                     (GroupChange__Actions__ModifyAnnouncementsOnlyAction         *message);
/* GroupChange__Actions methods */
void   group_change__actions__init
                     (GroupChange__Actions         *message);
/* GroupChange methods */
void   group_change__init
                     (GroupChange         *message);
size_t group_change__get_packed_size
                     (const GroupChange   *message);
size_t group_change__pack
                     (const GroupChange   *message,
                      uint8_t             *out);
size_t group_change__pack_to_buffer
                     (const GroupChange   *message,
                      ProtobufCBuffer     *buffer);
GroupChange *
       group_change__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   group_change__free_unpacked
                     (GroupChange *message,
                      ProtobufCAllocator *allocator);
/* GroupChanges__GroupChangeState methods */
void   group_changes__group_change_state__init
                     (GroupChanges__GroupChangeState         *message);
/* GroupChanges methods */
void   group_changes__init
                     (GroupChanges         *message);
size_t group_changes__get_packed_size
                     (const GroupChanges   *message);
size_t group_changes__pack
                     (const GroupChanges   *message,
                      uint8_t             *out);
size_t group_changes__pack_to_buffer
                     (const GroupChanges   *message,
                      ProtobufCBuffer     *buffer);
GroupChanges *
       group_changes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   group_changes__free_unpacked
                     (GroupChanges *message,
                      ProtobufCAllocator *allocator);
/* GroupAttributeBlob methods */
void   group_attribute_blob__init
                     (GroupAttributeBlob         *message);
size_t group_attribute_blob__get_packed_size
                     (const GroupAttributeBlob   *message);
size_t group_attribute_blob__pack
                     (const GroupAttributeBlob   *message,
                      uint8_t             *out);
size_t group_attribute_blob__pack_to_buffer
                     (const GroupAttributeBlob   *message,
                      ProtobufCBuffer     *buffer);
GroupAttributeBlob *
       group_attribute_blob__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   group_attribute_blob__free_unpacked
                     (GroupAttributeBlob *message,
                      ProtobufCAllocator *allocator);
/* GroupInviteLink__GroupInviteLinkContentsV1 methods */
void   group_invite_link__group_invite_link_contents_v1__init
                     (GroupInviteLink__GroupInviteLinkContentsV1         *message);
/* GroupInviteLink__GroupInviteLinkContentsV10 methods */
void   group_invite_link__group_invite_link_contents_v10__init
                     (GroupInviteLink__GroupInviteLinkContentsV10         *message);
/* GroupInviteLink methods */
void   group_invite_link__init
                     (GroupInviteLink         *message);
size_t group_invite_link__get_packed_size
                     (const GroupInviteLink   *message);
size_t group_invite_link__pack
                     (const GroupInviteLink   *message,
                      uint8_t             *out);
size_t group_invite_link__pack_to_buffer
                     (const GroupInviteLink   *message,
                      ProtobufCBuffer     *buffer);
GroupInviteLink *
       group_invite_link__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   group_invite_link__free_unpacked
                     (GroupInviteLink *message,
                      ProtobufCAllocator *allocator);
/* GroupJoinInfo methods */
void   group_join_info__init
                     (GroupJoinInfo         *message);
size_t group_join_info__get_packed_size
                     (const GroupJoinInfo   *message);
size_t group_join_info__pack
                     (const GroupJoinInfo   *message,
                      uint8_t             *out);
size_t group_join_info__pack_to_buffer
                     (const GroupJoinInfo   *message,
                      ProtobufCBuffer     *buffer);
GroupJoinInfo *
       group_join_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   group_join_info__free_unpacked
                     (GroupJoinInfo *message,
                      ProtobufCAllocator *allocator);
/* GroupExternalCredential methods */
void   group_external_credential__init
                     (GroupExternalCredential         *message);
size_t group_external_credential__get_packed_size
                     (const GroupExternalCredential   *message);
size_t group_external_credential__pack
                     (const GroupExternalCredential   *message,
                      uint8_t             *out);
size_t group_external_credential__pack_to_buffer
                     (const GroupExternalCredential   *message,
                      ProtobufCBuffer     *buffer);
GroupExternalCredential *
       group_external_credential__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   group_external_credential__free_unpacked
                     (GroupExternalCredential *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AvatarUploadAttributes_Closure)
                 (const AvatarUploadAttributes *message,
                  void *closure_data);
typedef void (*Member_Closure)
                 (const Member *message,
                  void *closure_data);
typedef void (*PendingMember_Closure)
                 (const PendingMember *message,
                  void *closure_data);
typedef void (*RequestingMember_Closure)
                 (const RequestingMember *message,
                  void *closure_data);
typedef void (*AccessControl_Closure)
                 (const AccessControl *message,
                  void *closure_data);
typedef void (*Group_Closure)
                 (const Group *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__AddMemberAction_Closure)
                 (const GroupChange__Actions__AddMemberAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__DeleteMemberAction_Closure)
                 (const GroupChange__Actions__DeleteMemberAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyMemberRoleAction_Closure)
                 (const GroupChange__Actions__ModifyMemberRoleAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyMemberProfileKeyAction_Closure)
                 (const GroupChange__Actions__ModifyMemberProfileKeyAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__AddPendingMemberAction_Closure)
                 (const GroupChange__Actions__AddPendingMemberAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__DeletePendingMemberAction_Closure)
                 (const GroupChange__Actions__DeletePendingMemberAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__PromotePendingMemberAction_Closure)
                 (const GroupChange__Actions__PromotePendingMemberAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__AddRequestingMemberAction_Closure)
                 (const GroupChange__Actions__AddRequestingMemberAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__DeleteRequestingMemberAction_Closure)
                 (const GroupChange__Actions__DeleteRequestingMemberAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__PromoteRequestingMemberAction_Closure)
                 (const GroupChange__Actions__PromoteRequestingMemberAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyTitleAction_Closure)
                 (const GroupChange__Actions__ModifyTitleAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyDescriptionAction_Closure)
                 (const GroupChange__Actions__ModifyDescriptionAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyAvatarAction_Closure)
                 (const GroupChange__Actions__ModifyAvatarAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyDisappearingMessagesTimerAction_Closure)
                 (const GroupChange__Actions__ModifyDisappearingMessagesTimerAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyAttributesAccessControlAction_Closure)
                 (const GroupChange__Actions__ModifyAttributesAccessControlAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyMembersAccessControlAction_Closure)
                 (const GroupChange__Actions__ModifyMembersAccessControlAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction_Closure)
                 (const GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyInviteLinkPasswordAction_Closure)
                 (const GroupChange__Actions__ModifyInviteLinkPasswordAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions__ModifyAnnouncementsOnlyAction_Closure)
                 (const GroupChange__Actions__ModifyAnnouncementsOnlyAction *message,
                  void *closure_data);
typedef void (*GroupChange__Actions_Closure)
                 (const GroupChange__Actions *message,
                  void *closure_data);
typedef void (*GroupChange_Closure)
                 (const GroupChange *message,
                  void *closure_data);
typedef void (*GroupChanges__GroupChangeState_Closure)
                 (const GroupChanges__GroupChangeState *message,
                  void *closure_data);
typedef void (*GroupChanges_Closure)
                 (const GroupChanges *message,
                  void *closure_data);
typedef void (*GroupAttributeBlob_Closure)
                 (const GroupAttributeBlob *message,
                  void *closure_data);
typedef void (*GroupInviteLink__GroupInviteLinkContentsV1_Closure)
                 (const GroupInviteLink__GroupInviteLinkContentsV1 *message,
                  void *closure_data);
typedef void (*GroupInviteLink__GroupInviteLinkContentsV10_Closure)
                 (const GroupInviteLink__GroupInviteLinkContentsV10 *message,
                  void *closure_data);
typedef void (*GroupInviteLink_Closure)
                 (const GroupInviteLink *message,
                  void *closure_data);
typedef void (*GroupJoinInfo_Closure)
                 (const GroupJoinInfo *message,
                  void *closure_data);
typedef void (*GroupExternalCredential_Closure)
                 (const GroupExternalCredential *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor avatar_upload_attributes__descriptor;
extern const ProtobufCMessageDescriptor member__descriptor;
extern const ProtobufCEnumDescriptor    member__role__descriptor;
extern const ProtobufCMessageDescriptor pending_member__descriptor;
extern const ProtobufCMessageDescriptor requesting_member__descriptor;
extern const ProtobufCMessageDescriptor access_control__descriptor;
extern const ProtobufCEnumDescriptor    access_control__access_required__descriptor;
extern const ProtobufCMessageDescriptor group__descriptor;
extern const ProtobufCMessageDescriptor group_change__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__add_member_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__delete_member_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_member_role_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_member_profile_key_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__add_pending_member_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__delete_pending_member_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__promote_pending_member_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__add_requesting_member_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__delete_requesting_member_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__promote_requesting_member_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_title_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_description_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_avatar_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_disappearing_messages_timer_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_attributes_access_control_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_members_access_control_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_add_from_invite_link_access_control_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_invite_link_password_action__descriptor;
extern const ProtobufCMessageDescriptor group_change__actions__modify_announcements_only_action__descriptor;
extern const ProtobufCMessageDescriptor group_changes__descriptor;
extern const ProtobufCMessageDescriptor group_changes__group_change_state__descriptor;
extern const ProtobufCMessageDescriptor group_attribute_blob__descriptor;
extern const ProtobufCMessageDescriptor group_invite_link__descriptor;
extern const ProtobufCMessageDescriptor group_invite_link__group_invite_link_contents_v1__descriptor;
extern const ProtobufCMessageDescriptor group_invite_link__group_invite_link_contents_v10__descriptor;
extern const ProtobufCMessageDescriptor group_join_info__descriptor;
extern const ProtobufCMessageDescriptor group_external_credential__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Groups_2eproto__INCLUDED */
