/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Groups.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Groups.pb-c.h"
void   avatar_upload_attributes__init
                     (AvatarUploadAttributes         *message)
{
  static const AvatarUploadAttributes init_value = AVATAR_UPLOAD_ATTRIBUTES__INIT;
  *message = init_value;
}
size_t avatar_upload_attributes__get_packed_size
                     (const AvatarUploadAttributes *message)
{
  assert(message->base.descriptor == &avatar_upload_attributes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t avatar_upload_attributes__pack
                     (const AvatarUploadAttributes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &avatar_upload_attributes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t avatar_upload_attributes__pack_to_buffer
                     (const AvatarUploadAttributes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &avatar_upload_attributes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AvatarUploadAttributes *
       avatar_upload_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AvatarUploadAttributes *)
     protobuf_c_message_unpack (&avatar_upload_attributes__descriptor,
                                allocator, len, data);
}
void   avatar_upload_attributes__free_unpacked
                     (AvatarUploadAttributes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &avatar_upload_attributes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   member__init
                     (Member         *message)
{
  static const Member init_value = MEMBER__INIT;
  *message = init_value;
}
size_t member__get_packed_size
                     (const Member *message)
{
  assert(message->base.descriptor == &member__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t member__pack
                     (const Member *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &member__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t member__pack_to_buffer
                     (const Member *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &member__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Member *
       member__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Member *)
     protobuf_c_message_unpack (&member__descriptor,
                                allocator, len, data);
}
void   member__free_unpacked
                     (Member *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &member__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pending_member__init
                     (PendingMember         *message)
{
  static const PendingMember init_value = PENDING_MEMBER__INIT;
  *message = init_value;
}
size_t pending_member__get_packed_size
                     (const PendingMember *message)
{
  assert(message->base.descriptor == &pending_member__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pending_member__pack
                     (const PendingMember *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pending_member__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pending_member__pack_to_buffer
                     (const PendingMember *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pending_member__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PendingMember *
       pending_member__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PendingMember *)
     protobuf_c_message_unpack (&pending_member__descriptor,
                                allocator, len, data);
}
void   pending_member__free_unpacked
                     (PendingMember *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pending_member__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   requesting_member__init
                     (RequestingMember         *message)
{
  static const RequestingMember init_value = REQUESTING_MEMBER__INIT;
  *message = init_value;
}
size_t requesting_member__get_packed_size
                     (const RequestingMember *message)
{
  assert(message->base.descriptor == &requesting_member__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requesting_member__pack
                     (const RequestingMember *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &requesting_member__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requesting_member__pack_to_buffer
                     (const RequestingMember *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &requesting_member__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestingMember *
       requesting_member__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestingMember *)
     protobuf_c_message_unpack (&requesting_member__descriptor,
                                allocator, len, data);
}
void   requesting_member__free_unpacked
                     (RequestingMember *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &requesting_member__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   access_control__init
                     (AccessControl         *message)
{
  static const AccessControl init_value = ACCESS_CONTROL__INIT;
  *message = init_value;
}
size_t access_control__get_packed_size
                     (const AccessControl *message)
{
  assert(message->base.descriptor == &access_control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t access_control__pack
                     (const AccessControl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &access_control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t access_control__pack_to_buffer
                     (const AccessControl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &access_control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AccessControl *
       access_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AccessControl *)
     protobuf_c_message_unpack (&access_control__descriptor,
                                allocator, len, data);
}
void   access_control__free_unpacked
                     (AccessControl *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &access_control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   group__init
                     (Group         *message)
{
  static const Group init_value = GROUP__INIT;
  *message = init_value;
}
size_t group__get_packed_size
                     (const Group *message)
{
  assert(message->base.descriptor == &group__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t group__pack
                     (const Group *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &group__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t group__pack_to_buffer
                     (const Group *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &group__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Group *
       group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Group *)
     protobuf_c_message_unpack (&group__descriptor,
                                allocator, len, data);
}
void   group__free_unpacked
                     (Group *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &group__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   group_change__actions__add_member_action__init
                     (GroupChange__Actions__AddMemberAction         *message)
{
  static const GroupChange__Actions__AddMemberAction init_value = GROUP_CHANGE__ACTIONS__ADD_MEMBER_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__delete_member_action__init
                     (GroupChange__Actions__DeleteMemberAction         *message)
{
  static const GroupChange__Actions__DeleteMemberAction init_value = GROUP_CHANGE__ACTIONS__DELETE_MEMBER_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_member_role_action__init
                     (GroupChange__Actions__ModifyMemberRoleAction         *message)
{
  static const GroupChange__Actions__ModifyMemberRoleAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_MEMBER_ROLE_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_member_profile_key_action__init
                     (GroupChange__Actions__ModifyMemberProfileKeyAction         *message)
{
  static const GroupChange__Actions__ModifyMemberProfileKeyAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_MEMBER_PROFILE_KEY_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__add_pending_member_action__init
                     (GroupChange__Actions__AddPendingMemberAction         *message)
{
  static const GroupChange__Actions__AddPendingMemberAction init_value = GROUP_CHANGE__ACTIONS__ADD_PENDING_MEMBER_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__delete_pending_member_action__init
                     (GroupChange__Actions__DeletePendingMemberAction         *message)
{
  static const GroupChange__Actions__DeletePendingMemberAction init_value = GROUP_CHANGE__ACTIONS__DELETE_PENDING_MEMBER_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__promote_pending_member_action__init
                     (GroupChange__Actions__PromotePendingMemberAction         *message)
{
  static const GroupChange__Actions__PromotePendingMemberAction init_value = GROUP_CHANGE__ACTIONS__PROMOTE_PENDING_MEMBER_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__add_requesting_member_action__init
                     (GroupChange__Actions__AddRequestingMemberAction         *message)
{
  static const GroupChange__Actions__AddRequestingMemberAction init_value = GROUP_CHANGE__ACTIONS__ADD_REQUESTING_MEMBER_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__delete_requesting_member_action__init
                     (GroupChange__Actions__DeleteRequestingMemberAction         *message)
{
  static const GroupChange__Actions__DeleteRequestingMemberAction init_value = GROUP_CHANGE__ACTIONS__DELETE_REQUESTING_MEMBER_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__promote_requesting_member_action__init
                     (GroupChange__Actions__PromoteRequestingMemberAction         *message)
{
  static const GroupChange__Actions__PromoteRequestingMemberAction init_value = GROUP_CHANGE__ACTIONS__PROMOTE_REQUESTING_MEMBER_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_title_action__init
                     (GroupChange__Actions__ModifyTitleAction         *message)
{
  static const GroupChange__Actions__ModifyTitleAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_TITLE_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_description_action__init
                     (GroupChange__Actions__ModifyDescriptionAction         *message)
{
  static const GroupChange__Actions__ModifyDescriptionAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_DESCRIPTION_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_avatar_action__init
                     (GroupChange__Actions__ModifyAvatarAction         *message)
{
  static const GroupChange__Actions__ModifyAvatarAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_AVATAR_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_disappearing_messages_timer_action__init
                     (GroupChange__Actions__ModifyDisappearingMessagesTimerAction         *message)
{
  static const GroupChange__Actions__ModifyDisappearingMessagesTimerAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_DISAPPEARING_MESSAGES_TIMER_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_attributes_access_control_action__init
                     (GroupChange__Actions__ModifyAttributesAccessControlAction         *message)
{
  static const GroupChange__Actions__ModifyAttributesAccessControlAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_ATTRIBUTES_ACCESS_CONTROL_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_members_access_control_action__init
                     (GroupChange__Actions__ModifyMembersAccessControlAction         *message)
{
  static const GroupChange__Actions__ModifyMembersAccessControlAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_MEMBERS_ACCESS_CONTROL_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_add_from_invite_link_access_control_action__init
                     (GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction         *message)
{
  static const GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_ADD_FROM_INVITE_LINK_ACCESS_CONTROL_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_invite_link_password_action__init
                     (GroupChange__Actions__ModifyInviteLinkPasswordAction         *message)
{
  static const GroupChange__Actions__ModifyInviteLinkPasswordAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_INVITE_LINK_PASSWORD_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__modify_announcements_only_action__init
                     (GroupChange__Actions__ModifyAnnouncementsOnlyAction         *message)
{
  static const GroupChange__Actions__ModifyAnnouncementsOnlyAction init_value = GROUP_CHANGE__ACTIONS__MODIFY_ANNOUNCEMENTS_ONLY_ACTION__INIT;
  *message = init_value;
}
void   group_change__actions__init
                     (GroupChange__Actions         *message)
{
  static const GroupChange__Actions init_value = GROUP_CHANGE__ACTIONS__INIT;
  *message = init_value;
}
void   group_change__init
                     (GroupChange         *message)
{
  static const GroupChange init_value = GROUP_CHANGE__INIT;
  *message = init_value;
}
size_t group_change__get_packed_size
                     (const GroupChange *message)
{
  assert(message->base.descriptor == &group_change__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t group_change__pack
                     (const GroupChange *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &group_change__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t group_change__pack_to_buffer
                     (const GroupChange *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &group_change__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GroupChange *
       group_change__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GroupChange *)
     protobuf_c_message_unpack (&group_change__descriptor,
                                allocator, len, data);
}
void   group_change__free_unpacked
                     (GroupChange *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &group_change__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   group_changes__group_change_state__init
                     (GroupChanges__GroupChangeState         *message)
{
  static const GroupChanges__GroupChangeState init_value = GROUP_CHANGES__GROUP_CHANGE_STATE__INIT;
  *message = init_value;
}
void   group_changes__init
                     (GroupChanges         *message)
{
  static const GroupChanges init_value = GROUP_CHANGES__INIT;
  *message = init_value;
}
size_t group_changes__get_packed_size
                     (const GroupChanges *message)
{
  assert(message->base.descriptor == &group_changes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t group_changes__pack
                     (const GroupChanges *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &group_changes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t group_changes__pack_to_buffer
                     (const GroupChanges *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &group_changes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GroupChanges *
       group_changes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GroupChanges *)
     protobuf_c_message_unpack (&group_changes__descriptor,
                                allocator, len, data);
}
void   group_changes__free_unpacked
                     (GroupChanges *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &group_changes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   group_attribute_blob__init
                     (GroupAttributeBlob         *message)
{
  static const GroupAttributeBlob init_value = GROUP_ATTRIBUTE_BLOB__INIT;
  *message = init_value;
}
size_t group_attribute_blob__get_packed_size
                     (const GroupAttributeBlob *message)
{
  assert(message->base.descriptor == &group_attribute_blob__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t group_attribute_blob__pack
                     (const GroupAttributeBlob *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &group_attribute_blob__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t group_attribute_blob__pack_to_buffer
                     (const GroupAttributeBlob *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &group_attribute_blob__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GroupAttributeBlob *
       group_attribute_blob__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GroupAttributeBlob *)
     protobuf_c_message_unpack (&group_attribute_blob__descriptor,
                                allocator, len, data);
}
void   group_attribute_blob__free_unpacked
                     (GroupAttributeBlob *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &group_attribute_blob__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   group_invite_link__group_invite_link_contents_v1__init
                     (GroupInviteLink__GroupInviteLinkContentsV1         *message)
{
  static const GroupInviteLink__GroupInviteLinkContentsV1 init_value = GROUP_INVITE_LINK__GROUP_INVITE_LINK_CONTENTS_V1__INIT;
  *message = init_value;
}
void   group_invite_link__group_invite_link_contents_v10__init
                     (GroupInviteLink__GroupInviteLinkContentsV10         *message)
{
  static const GroupInviteLink__GroupInviteLinkContentsV10 init_value = GROUP_INVITE_LINK__GROUP_INVITE_LINK_CONTENTS_V10__INIT;
  *message = init_value;
}
void   group_invite_link__init
                     (GroupInviteLink         *message)
{
  static const GroupInviteLink init_value = GROUP_INVITE_LINK__INIT;
  *message = init_value;
}
size_t group_invite_link__get_packed_size
                     (const GroupInviteLink *message)
{
  assert(message->base.descriptor == &group_invite_link__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t group_invite_link__pack
                     (const GroupInviteLink *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &group_invite_link__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t group_invite_link__pack_to_buffer
                     (const GroupInviteLink *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &group_invite_link__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GroupInviteLink *
       group_invite_link__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GroupInviteLink *)
     protobuf_c_message_unpack (&group_invite_link__descriptor,
                                allocator, len, data);
}
void   group_invite_link__free_unpacked
                     (GroupInviteLink *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &group_invite_link__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   group_join_info__init
                     (GroupJoinInfo         *message)
{
  static const GroupJoinInfo init_value = GROUP_JOIN_INFO__INIT;
  *message = init_value;
}
size_t group_join_info__get_packed_size
                     (const GroupJoinInfo *message)
{
  assert(message->base.descriptor == &group_join_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t group_join_info__pack
                     (const GroupJoinInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &group_join_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t group_join_info__pack_to_buffer
                     (const GroupJoinInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &group_join_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GroupJoinInfo *
       group_join_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GroupJoinInfo *)
     protobuf_c_message_unpack (&group_join_info__descriptor,
                                allocator, len, data);
}
void   group_join_info__free_unpacked
                     (GroupJoinInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &group_join_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   group_external_credential__init
                     (GroupExternalCredential         *message)
{
  static const GroupExternalCredential init_value = GROUP_EXTERNAL_CREDENTIAL__INIT;
  *message = init_value;
}
size_t group_external_credential__get_packed_size
                     (const GroupExternalCredential *message)
{
  assert(message->base.descriptor == &group_external_credential__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t group_external_credential__pack
                     (const GroupExternalCredential *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &group_external_credential__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t group_external_credential__pack_to_buffer
                     (const GroupExternalCredential *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &group_external_credential__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GroupExternalCredential *
       group_external_credential__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GroupExternalCredential *)
     protobuf_c_message_unpack (&group_external_credential__descriptor,
                                allocator, len, data);
}
void   group_external_credential__free_unpacked
                     (GroupExternalCredential *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &group_external_credential__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor avatar_upload_attributes__field_descriptors[7] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AvatarUploadAttributes, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "credential",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AvatarUploadAttributes, credential),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acl",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AvatarUploadAttributes, acl),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "algorithm",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AvatarUploadAttributes, algorithm),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "date",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AvatarUploadAttributes, date),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "policy",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AvatarUploadAttributes, policy),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AvatarUploadAttributes, signature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned avatar_upload_attributes__field_indices_by_name[] = {
  2,   /* field[2] = acl */
  3,   /* field[3] = algorithm */
  1,   /* field[1] = credential */
  4,   /* field[4] = date */
  0,   /* field[0] = key */
  5,   /* field[5] = policy */
  6,   /* field[6] = signature */
};
static const ProtobufCIntRange avatar_upload_attributes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor avatar_upload_attributes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AvatarUploadAttributes",
  "AvatarUploadAttributes",
  "AvatarUploadAttributes",
  "",
  sizeof(AvatarUploadAttributes),
  7,
  avatar_upload_attributes__field_descriptors,
  avatar_upload_attributes__field_indices_by_name,
  1,  avatar_upload_attributes__number_ranges,
  (ProtobufCMessageInit) avatar_upload_attributes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue member__role__enum_values_by_number[3] =
{
  { "UNKNOWN", "MEMBER__ROLE__UNKNOWN", 0 },
  { "DEFAULT", "MEMBER__ROLE__DEFAULT", 1 },
  { "ADMINISTRATOR", "MEMBER__ROLE__ADMINISTRATOR", 2 },
};
static const ProtobufCIntRange member__role__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex member__role__enum_values_by_name[3] =
{
  { "ADMINISTRATOR", 2 },
  { "DEFAULT", 1 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor member__role__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Member.Role",
  "Role",
  "Member__Role",
  "",
  3,
  member__role__enum_values_by_number,
  3,
  member__role__enum_values_by_name,
  1,
  member__role__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor member__field_descriptors[5] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Member, userid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "role",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Member, role),
    &member__role__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "profileKey",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Member, profilekey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "presentation",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Member, presentation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "joinedAtRevision",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Member, joinedatrevision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned member__field_indices_by_name[] = {
  4,   /* field[4] = joinedAtRevision */
  3,   /* field[3] = presentation */
  2,   /* field[2] = profileKey */
  1,   /* field[1] = role */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange member__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor member__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Member",
  "Member",
  "Member",
  "",
  sizeof(Member),
  5,
  member__field_descriptors,
  member__field_indices_by_name,
  1,  member__number_ranges,
  (ProtobufCMessageInit) member__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pending_member__field_descriptors[3] =
{
  {
    "member",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PendingMember, member),
    &member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addedByUserId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PendingMember, addedbyuserid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PendingMember, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pending_member__field_indices_by_name[] = {
  1,   /* field[1] = addedByUserId */
  0,   /* field[0] = member */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange pending_member__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pending_member__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PendingMember",
  "PendingMember",
  "PendingMember",
  "",
  sizeof(PendingMember),
  3,
  pending_member__field_descriptors,
  pending_member__field_indices_by_name,
  1,  pending_member__number_ranges,
  (ProtobufCMessageInit) pending_member__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor requesting_member__field_descriptors[4] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RequestingMember, userid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "profileKey",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RequestingMember, profilekey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "presentation",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RequestingMember, presentation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RequestingMember, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned requesting_member__field_indices_by_name[] = {
  2,   /* field[2] = presentation */
  1,   /* field[1] = profileKey */
  3,   /* field[3] = timestamp */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange requesting_member__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor requesting_member__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RequestingMember",
  "RequestingMember",
  "RequestingMember",
  "",
  sizeof(RequestingMember),
  4,
  requesting_member__field_descriptors,
  requesting_member__field_indices_by_name,
  1,  requesting_member__number_ranges,
  (ProtobufCMessageInit) requesting_member__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue access_control__access_required__enum_values_by_number[5] =
{
  { "UNKNOWN", "ACCESS_CONTROL__ACCESS_REQUIRED__UNKNOWN", 0 },
  { "ANY", "ACCESS_CONTROL__ACCESS_REQUIRED__ANY", 1 },
  { "MEMBER", "ACCESS_CONTROL__ACCESS_REQUIRED__MEMBER", 2 },
  { "ADMINISTRATOR", "ACCESS_CONTROL__ACCESS_REQUIRED__ADMINISTRATOR", 3 },
  { "UNSATISFIABLE", "ACCESS_CONTROL__ACCESS_REQUIRED__UNSATISFIABLE", 4 },
};
static const ProtobufCIntRange access_control__access_required__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex access_control__access_required__enum_values_by_name[5] =
{
  { "ADMINISTRATOR", 3 },
  { "ANY", 1 },
  { "MEMBER", 2 },
  { "UNKNOWN", 0 },
  { "UNSATISFIABLE", 4 },
};
const ProtobufCEnumDescriptor access_control__access_required__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AccessControl.AccessRequired",
  "AccessRequired",
  "AccessControl__AccessRequired",
  "",
  5,
  access_control__access_required__enum_values_by_number,
  5,
  access_control__access_required__enum_values_by_name,
  1,
  access_control__access_required__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor access_control__field_descriptors[3] =
{
  {
    "attributes",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AccessControl, attributes),
    &access_control__access_required__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "members",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AccessControl, members),
    &access_control__access_required__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addFromInviteLink",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AccessControl, addfrominvitelink),
    &access_control__access_required__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned access_control__field_indices_by_name[] = {
  2,   /* field[2] = addFromInviteLink */
  0,   /* field[0] = attributes */
  1,   /* field[1] = members */
};
static const ProtobufCIntRange access_control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor access_control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AccessControl",
  "AccessControl",
  "AccessControl",
  "",
  sizeof(AccessControl),
  3,
  access_control__field_descriptors,
  access_control__field_indices_by_name,
  1,  access_control__number_ranges,
  (ProtobufCMessageInit) access_control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group__field_descriptors[12] =
{
  {
    "publicKey",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Group, publickey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "title",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Group, title),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avatar",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Group, avatar),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disappearingMessagesTimer",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Group, disappearingmessagestimer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accessControl",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Group, accesscontrol),
    &access_control__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "revision",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Group, revision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "members",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Group, n_members),
    offsetof(Group, members),
    &member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pendingMembers",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Group, n_pendingmembers),
    offsetof(Group, pendingmembers),
    &pending_member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requestingMembers",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Group, n_requestingmembers),
    offsetof(Group, requestingmembers),
    &requesting_member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inviteLinkPassword",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Group, invitelinkpassword),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Group, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "announcementsOnly",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Group, announcementsonly),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group__field_indices_by_name[] = {
  4,   /* field[4] = accessControl */
  11,   /* field[11] = announcementsOnly */
  2,   /* field[2] = avatar */
  10,   /* field[10] = description */
  3,   /* field[3] = disappearingMessagesTimer */
  9,   /* field[9] = inviteLinkPassword */
  6,   /* field[6] = members */
  7,   /* field[7] = pendingMembers */
  0,   /* field[0] = publicKey */
  8,   /* field[8] = requestingMembers */
  5,   /* field[5] = revision */
  1,   /* field[1] = title */
};
static const ProtobufCIntRange group__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor group__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Group",
  "Group",
  "Group",
  "",
  sizeof(Group),
  12,
  group__field_descriptors,
  group__field_indices_by_name,
  1,  group__number_ranges,
  (ProtobufCMessageInit) group__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__add_member_action__field_descriptors[2] =
{
  {
    "added",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__AddMemberAction, added),
    &member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "joinFromInviteLink",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__AddMemberAction, joinfrominvitelink),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__add_member_action__field_indices_by_name[] = {
  0,   /* field[0] = added */
  1,   /* field[1] = joinFromInviteLink */
};
static const ProtobufCIntRange group_change__actions__add_member_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor group_change__actions__add_member_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.AddMemberAction",
  "AddMemberAction",
  "GroupChange__Actions__AddMemberAction",
  "",
  sizeof(GroupChange__Actions__AddMemberAction),
  2,
  group_change__actions__add_member_action__field_descriptors,
  group_change__actions__add_member_action__field_indices_by_name,
  1,  group_change__actions__add_member_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__add_member_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__delete_member_action__field_descriptors[1] =
{
  {
    "deletedUserId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__DeleteMemberAction, deleteduserid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__delete_member_action__field_indices_by_name[] = {
  0,   /* field[0] = deletedUserId */
};
static const ProtobufCIntRange group_change__actions__delete_member_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__delete_member_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.DeleteMemberAction",
  "DeleteMemberAction",
  "GroupChange__Actions__DeleteMemberAction",
  "",
  sizeof(GroupChange__Actions__DeleteMemberAction),
  1,
  group_change__actions__delete_member_action__field_descriptors,
  group_change__actions__delete_member_action__field_indices_by_name,
  1,  group_change__actions__delete_member_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__delete_member_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_member_role_action__field_descriptors[2] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyMemberRoleAction, userid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "role",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyMemberRoleAction, role),
    &member__role__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_member_role_action__field_indices_by_name[] = {
  1,   /* field[1] = role */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange group_change__actions__modify_member_role_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_member_role_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyMemberRoleAction",
  "ModifyMemberRoleAction",
  "GroupChange__Actions__ModifyMemberRoleAction",
  "",
  sizeof(GroupChange__Actions__ModifyMemberRoleAction),
  2,
  group_change__actions__modify_member_role_action__field_descriptors,
  group_change__actions__modify_member_role_action__field_indices_by_name,
  1,  group_change__actions__modify_member_role_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_member_role_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_member_profile_key_action__field_descriptors[1] =
{
  {
    "presentation",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyMemberProfileKeyAction, presentation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_member_profile_key_action__field_indices_by_name[] = {
  0,   /* field[0] = presentation */
};
static const ProtobufCIntRange group_change__actions__modify_member_profile_key_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_member_profile_key_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyMemberProfileKeyAction",
  "ModifyMemberProfileKeyAction",
  "GroupChange__Actions__ModifyMemberProfileKeyAction",
  "",
  sizeof(GroupChange__Actions__ModifyMemberProfileKeyAction),
  1,
  group_change__actions__modify_member_profile_key_action__field_descriptors,
  group_change__actions__modify_member_profile_key_action__field_indices_by_name,
  1,  group_change__actions__modify_member_profile_key_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_member_profile_key_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__add_pending_member_action__field_descriptors[1] =
{
  {
    "added",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__AddPendingMemberAction, added),
    &pending_member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__add_pending_member_action__field_indices_by_name[] = {
  0,   /* field[0] = added */
};
static const ProtobufCIntRange group_change__actions__add_pending_member_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__add_pending_member_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.AddPendingMemberAction",
  "AddPendingMemberAction",
  "GroupChange__Actions__AddPendingMemberAction",
  "",
  sizeof(GroupChange__Actions__AddPendingMemberAction),
  1,
  group_change__actions__add_pending_member_action__field_descriptors,
  group_change__actions__add_pending_member_action__field_indices_by_name,
  1,  group_change__actions__add_pending_member_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__add_pending_member_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__delete_pending_member_action__field_descriptors[1] =
{
  {
    "deletedUserId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__DeletePendingMemberAction, deleteduserid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__delete_pending_member_action__field_indices_by_name[] = {
  0,   /* field[0] = deletedUserId */
};
static const ProtobufCIntRange group_change__actions__delete_pending_member_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__delete_pending_member_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.DeletePendingMemberAction",
  "DeletePendingMemberAction",
  "GroupChange__Actions__DeletePendingMemberAction",
  "",
  sizeof(GroupChange__Actions__DeletePendingMemberAction),
  1,
  group_change__actions__delete_pending_member_action__field_descriptors,
  group_change__actions__delete_pending_member_action__field_indices_by_name,
  1,  group_change__actions__delete_pending_member_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__delete_pending_member_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__promote_pending_member_action__field_descriptors[1] =
{
  {
    "presentation",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__PromotePendingMemberAction, presentation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__promote_pending_member_action__field_indices_by_name[] = {
  0,   /* field[0] = presentation */
};
static const ProtobufCIntRange group_change__actions__promote_pending_member_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__promote_pending_member_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.PromotePendingMemberAction",
  "PromotePendingMemberAction",
  "GroupChange__Actions__PromotePendingMemberAction",
  "",
  sizeof(GroupChange__Actions__PromotePendingMemberAction),
  1,
  group_change__actions__promote_pending_member_action__field_descriptors,
  group_change__actions__promote_pending_member_action__field_indices_by_name,
  1,  group_change__actions__promote_pending_member_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__promote_pending_member_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__add_requesting_member_action__field_descriptors[1] =
{
  {
    "added",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__AddRequestingMemberAction, added),
    &requesting_member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__add_requesting_member_action__field_indices_by_name[] = {
  0,   /* field[0] = added */
};
static const ProtobufCIntRange group_change__actions__add_requesting_member_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__add_requesting_member_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.AddRequestingMemberAction",
  "AddRequestingMemberAction",
  "GroupChange__Actions__AddRequestingMemberAction",
  "",
  sizeof(GroupChange__Actions__AddRequestingMemberAction),
  1,
  group_change__actions__add_requesting_member_action__field_descriptors,
  group_change__actions__add_requesting_member_action__field_indices_by_name,
  1,  group_change__actions__add_requesting_member_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__add_requesting_member_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__delete_requesting_member_action__field_descriptors[1] =
{
  {
    "deletedUserId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__DeleteRequestingMemberAction, deleteduserid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__delete_requesting_member_action__field_indices_by_name[] = {
  0,   /* field[0] = deletedUserId */
};
static const ProtobufCIntRange group_change__actions__delete_requesting_member_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__delete_requesting_member_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.DeleteRequestingMemberAction",
  "DeleteRequestingMemberAction",
  "GroupChange__Actions__DeleteRequestingMemberAction",
  "",
  sizeof(GroupChange__Actions__DeleteRequestingMemberAction),
  1,
  group_change__actions__delete_requesting_member_action__field_descriptors,
  group_change__actions__delete_requesting_member_action__field_indices_by_name,
  1,  group_change__actions__delete_requesting_member_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__delete_requesting_member_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__promote_requesting_member_action__field_descriptors[2] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__PromoteRequestingMemberAction, userid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "role",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__PromoteRequestingMemberAction, role),
    &member__role__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__promote_requesting_member_action__field_indices_by_name[] = {
  1,   /* field[1] = role */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange group_change__actions__promote_requesting_member_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor group_change__actions__promote_requesting_member_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.PromoteRequestingMemberAction",
  "PromoteRequestingMemberAction",
  "GroupChange__Actions__PromoteRequestingMemberAction",
  "",
  sizeof(GroupChange__Actions__PromoteRequestingMemberAction),
  2,
  group_change__actions__promote_requesting_member_action__field_descriptors,
  group_change__actions__promote_requesting_member_action__field_indices_by_name,
  1,  group_change__actions__promote_requesting_member_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__promote_requesting_member_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_title_action__field_descriptors[1] =
{
  {
    "title",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyTitleAction, title),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_title_action__field_indices_by_name[] = {
  0,   /* field[0] = title */
};
static const ProtobufCIntRange group_change__actions__modify_title_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_title_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyTitleAction",
  "ModifyTitleAction",
  "GroupChange__Actions__ModifyTitleAction",
  "",
  sizeof(GroupChange__Actions__ModifyTitleAction),
  1,
  group_change__actions__modify_title_action__field_descriptors,
  group_change__actions__modify_title_action__field_indices_by_name,
  1,  group_change__actions__modify_title_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_title_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_description_action__field_descriptors[1] =
{
  {
    "description",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyDescriptionAction, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_description_action__field_indices_by_name[] = {
  0,   /* field[0] = description */
};
static const ProtobufCIntRange group_change__actions__modify_description_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_description_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyDescriptionAction",
  "ModifyDescriptionAction",
  "GroupChange__Actions__ModifyDescriptionAction",
  "",
  sizeof(GroupChange__Actions__ModifyDescriptionAction),
  1,
  group_change__actions__modify_description_action__field_descriptors,
  group_change__actions__modify_description_action__field_indices_by_name,
  1,  group_change__actions__modify_description_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_description_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_avatar_action__field_descriptors[1] =
{
  {
    "avatar",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyAvatarAction, avatar),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_avatar_action__field_indices_by_name[] = {
  0,   /* field[0] = avatar */
};
static const ProtobufCIntRange group_change__actions__modify_avatar_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_avatar_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyAvatarAction",
  "ModifyAvatarAction",
  "GroupChange__Actions__ModifyAvatarAction",
  "",
  sizeof(GroupChange__Actions__ModifyAvatarAction),
  1,
  group_change__actions__modify_avatar_action__field_descriptors,
  group_change__actions__modify_avatar_action__field_indices_by_name,
  1,  group_change__actions__modify_avatar_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_avatar_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_disappearing_messages_timer_action__field_descriptors[1] =
{
  {
    "timer",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyDisappearingMessagesTimerAction, timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_disappearing_messages_timer_action__field_indices_by_name[] = {
  0,   /* field[0] = timer */
};
static const ProtobufCIntRange group_change__actions__modify_disappearing_messages_timer_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_disappearing_messages_timer_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyDisappearingMessagesTimerAction",
  "ModifyDisappearingMessagesTimerAction",
  "GroupChange__Actions__ModifyDisappearingMessagesTimerAction",
  "",
  sizeof(GroupChange__Actions__ModifyDisappearingMessagesTimerAction),
  1,
  group_change__actions__modify_disappearing_messages_timer_action__field_descriptors,
  group_change__actions__modify_disappearing_messages_timer_action__field_indices_by_name,
  1,  group_change__actions__modify_disappearing_messages_timer_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_disappearing_messages_timer_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_attributes_access_control_action__field_descriptors[1] =
{
  {
    "attributesAccess",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyAttributesAccessControlAction, attributesaccess),
    &access_control__access_required__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_attributes_access_control_action__field_indices_by_name[] = {
  0,   /* field[0] = attributesAccess */
};
static const ProtobufCIntRange group_change__actions__modify_attributes_access_control_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_attributes_access_control_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyAttributesAccessControlAction",
  "ModifyAttributesAccessControlAction",
  "GroupChange__Actions__ModifyAttributesAccessControlAction",
  "",
  sizeof(GroupChange__Actions__ModifyAttributesAccessControlAction),
  1,
  group_change__actions__modify_attributes_access_control_action__field_descriptors,
  group_change__actions__modify_attributes_access_control_action__field_indices_by_name,
  1,  group_change__actions__modify_attributes_access_control_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_attributes_access_control_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_members_access_control_action__field_descriptors[1] =
{
  {
    "membersAccess",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyMembersAccessControlAction, membersaccess),
    &access_control__access_required__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_members_access_control_action__field_indices_by_name[] = {
  0,   /* field[0] = membersAccess */
};
static const ProtobufCIntRange group_change__actions__modify_members_access_control_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_members_access_control_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyMembersAccessControlAction",
  "ModifyMembersAccessControlAction",
  "GroupChange__Actions__ModifyMembersAccessControlAction",
  "",
  sizeof(GroupChange__Actions__ModifyMembersAccessControlAction),
  1,
  group_change__actions__modify_members_access_control_action__field_descriptors,
  group_change__actions__modify_members_access_control_action__field_indices_by_name,
  1,  group_change__actions__modify_members_access_control_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_members_access_control_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_add_from_invite_link_access_control_action__field_descriptors[1] =
{
  {
    "addFromInviteLinkAccess",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction, addfrominvitelinkaccess),
    &access_control__access_required__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_add_from_invite_link_access_control_action__field_indices_by_name[] = {
  0,   /* field[0] = addFromInviteLinkAccess */
};
static const ProtobufCIntRange group_change__actions__modify_add_from_invite_link_access_control_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_add_from_invite_link_access_control_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyAddFromInviteLinkAccessControlAction",
  "ModifyAddFromInviteLinkAccessControlAction",
  "GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction",
  "",
  sizeof(GroupChange__Actions__ModifyAddFromInviteLinkAccessControlAction),
  1,
  group_change__actions__modify_add_from_invite_link_access_control_action__field_descriptors,
  group_change__actions__modify_add_from_invite_link_access_control_action__field_indices_by_name,
  1,  group_change__actions__modify_add_from_invite_link_access_control_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_add_from_invite_link_access_control_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_invite_link_password_action__field_descriptors[1] =
{
  {
    "inviteLinkPassword",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyInviteLinkPasswordAction, invitelinkpassword),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_invite_link_password_action__field_indices_by_name[] = {
  0,   /* field[0] = inviteLinkPassword */
};
static const ProtobufCIntRange group_change__actions__modify_invite_link_password_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_invite_link_password_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyInviteLinkPasswordAction",
  "ModifyInviteLinkPasswordAction",
  "GroupChange__Actions__ModifyInviteLinkPasswordAction",
  "",
  sizeof(GroupChange__Actions__ModifyInviteLinkPasswordAction),
  1,
  group_change__actions__modify_invite_link_password_action__field_descriptors,
  group_change__actions__modify_invite_link_password_action__field_indices_by_name,
  1,  group_change__actions__modify_invite_link_password_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_invite_link_password_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__modify_announcements_only_action__field_descriptors[1] =
{
  {
    "announcementsOnly",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions__ModifyAnnouncementsOnlyAction, announcementsonly),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__modify_announcements_only_action__field_indices_by_name[] = {
  0,   /* field[0] = announcementsOnly */
};
static const ProtobufCIntRange group_change__actions__modify_announcements_only_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_change__actions__modify_announcements_only_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions.ModifyAnnouncementsOnlyAction",
  "ModifyAnnouncementsOnlyAction",
  "GroupChange__Actions__ModifyAnnouncementsOnlyAction",
  "",
  sizeof(GroupChange__Actions__ModifyAnnouncementsOnlyAction),
  1,
  group_change__actions__modify_announcements_only_action__field_descriptors,
  group_change__actions__modify_announcements_only_action__field_indices_by_name,
  1,  group_change__actions__modify_announcements_only_action__number_ranges,
  (ProtobufCMessageInit) group_change__actions__modify_announcements_only_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__actions__field_descriptors[21] =
{
  {
    "sourceUuid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, sourceuuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "revision",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, revision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addMembers",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChange__Actions, n_addmembers),
    offsetof(GroupChange__Actions, addmembers),
    &group_change__actions__add_member_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deleteMembers",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChange__Actions, n_deletemembers),
    offsetof(GroupChange__Actions, deletemembers),
    &group_change__actions__delete_member_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyMemberRoles",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChange__Actions, n_modifymemberroles),
    offsetof(GroupChange__Actions, modifymemberroles),
    &group_change__actions__modify_member_role_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyMemberProfileKeys",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChange__Actions, n_modifymemberprofilekeys),
    offsetof(GroupChange__Actions, modifymemberprofilekeys),
    &group_change__actions__modify_member_profile_key_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addPendingMembers",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChange__Actions, n_addpendingmembers),
    offsetof(GroupChange__Actions, addpendingmembers),
    &group_change__actions__add_pending_member_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deletePendingMembers",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChange__Actions, n_deletependingmembers),
    offsetof(GroupChange__Actions, deletependingmembers),
    &group_change__actions__delete_pending_member_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "promotePendingMembers",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChange__Actions, n_promotependingmembers),
    offsetof(GroupChange__Actions, promotependingmembers),
    &group_change__actions__promote_pending_member_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyTitle",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, modifytitle),
    &group_change__actions__modify_title_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyAvatar",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, modifyavatar),
    &group_change__actions__modify_avatar_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyDisappearingMessagesTimer",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, modifydisappearingmessagestimer),
    &group_change__actions__modify_disappearing_messages_timer_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyAttributesAccess",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, modifyattributesaccess),
    &group_change__actions__modify_attributes_access_control_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyMemberAccess",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, modifymemberaccess),
    &group_change__actions__modify_members_access_control_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyAddFromInviteLinkAccess",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, modifyaddfrominvitelinkaccess),
    &group_change__actions__modify_add_from_invite_link_access_control_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addRequestingMembers",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChange__Actions, n_addrequestingmembers),
    offsetof(GroupChange__Actions, addrequestingmembers),
    &group_change__actions__add_requesting_member_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deleteRequestingMembers",
    17,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChange__Actions, n_deleterequestingmembers),
    offsetof(GroupChange__Actions, deleterequestingmembers),
    &group_change__actions__delete_requesting_member_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "promoteRequestingMembers",
    18,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChange__Actions, n_promoterequestingmembers),
    offsetof(GroupChange__Actions, promoterequestingmembers),
    &group_change__actions__promote_requesting_member_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyInviteLinkPassword",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, modifyinvitelinkpassword),
    &group_change__actions__modify_invite_link_password_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyDescription",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, modifydescription),
    &group_change__actions__modify_description_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyAnnouncementsOnly",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChange__Actions, modifyannouncementsonly),
    &group_change__actions__modify_announcements_only_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__actions__field_indices_by_name[] = {
  2,   /* field[2] = addMembers */
  6,   /* field[6] = addPendingMembers */
  15,   /* field[15] = addRequestingMembers */
  3,   /* field[3] = deleteMembers */
  7,   /* field[7] = deletePendingMembers */
  16,   /* field[16] = deleteRequestingMembers */
  14,   /* field[14] = modifyAddFromInviteLinkAccess */
  20,   /* field[20] = modifyAnnouncementsOnly */
  12,   /* field[12] = modifyAttributesAccess */
  10,   /* field[10] = modifyAvatar */
  19,   /* field[19] = modifyDescription */
  11,   /* field[11] = modifyDisappearingMessagesTimer */
  18,   /* field[18] = modifyInviteLinkPassword */
  13,   /* field[13] = modifyMemberAccess */
  5,   /* field[5] = modifyMemberProfileKeys */
  4,   /* field[4] = modifyMemberRoles */
  9,   /* field[9] = modifyTitle */
  8,   /* field[8] = promotePendingMembers */
  17,   /* field[17] = promoteRequestingMembers */
  1,   /* field[1] = revision */
  0,   /* field[0] = sourceUuid */
};
static const ProtobufCIntRange group_change__actions__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 21 }
};
const ProtobufCMessageDescriptor group_change__actions__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange.Actions",
  "Actions",
  "GroupChange__Actions",
  "",
  sizeof(GroupChange__Actions),
  21,
  group_change__actions__field_descriptors,
  group_change__actions__field_indices_by_name,
  1,  group_change__actions__number_ranges,
  (ProtobufCMessageInit) group_change__actions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_change__field_descriptors[3] =
{
  {
    "actions",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange, actions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serverSignature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupChange, serversignature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "changeEpoch",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GroupChange, changeepoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_change__field_indices_by_name[] = {
  0,   /* field[0] = actions */
  2,   /* field[2] = changeEpoch */
  1,   /* field[1] = serverSignature */
};
static const ProtobufCIntRange group_change__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor group_change__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChange",
  "GroupChange",
  "GroupChange",
  "",
  sizeof(GroupChange),
  3,
  group_change__field_descriptors,
  group_change__field_indices_by_name,
  1,  group_change__number_ranges,
  (ProtobufCMessageInit) group_change__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_changes__group_change_state__field_descriptors[2] =
{
  {
    "groupChange",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChanges__GroupChangeState, groupchange),
    &group_change__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "groupState",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GroupChanges__GroupChangeState, groupstate),
    &group__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_changes__group_change_state__field_indices_by_name[] = {
  0,   /* field[0] = groupChange */
  1,   /* field[1] = groupState */
};
static const ProtobufCIntRange group_changes__group_change_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor group_changes__group_change_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChanges.GroupChangeState",
  "GroupChangeState",
  "GroupChanges__GroupChangeState",
  "",
  sizeof(GroupChanges__GroupChangeState),
  2,
  group_changes__group_change_state__field_descriptors,
  group_changes__group_change_state__field_indices_by_name,
  1,  group_changes__group_change_state__number_ranges,
  (ProtobufCMessageInit) group_changes__group_change_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_changes__field_descriptors[1] =
{
  {
    "groupChanges",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupChanges, n_groupchanges),
    offsetof(GroupChanges, groupchanges),
    &group_changes__group_change_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_changes__field_indices_by_name[] = {
  0,   /* field[0] = groupChanges */
};
static const ProtobufCIntRange group_changes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_changes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupChanges",
  "GroupChanges",
  "GroupChanges",
  "",
  sizeof(GroupChanges),
  1,
  group_changes__field_descriptors,
  group_changes__field_indices_by_name,
  1,  group_changes__number_ranges,
  (ProtobufCMessageInit) group_changes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_attribute_blob__field_descriptors[4] =
{
  {
    "title",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(GroupAttributeBlob, content_case),
    offsetof(GroupAttributeBlob, title),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avatar",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(GroupAttributeBlob, content_case),
    offsetof(GroupAttributeBlob, avatar),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disappearingMessagesDuration",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(GroupAttributeBlob, content_case),
    offsetof(GroupAttributeBlob, disappearingmessagesduration),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(GroupAttributeBlob, content_case),
    offsetof(GroupAttributeBlob, description),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_attribute_blob__field_indices_by_name[] = {
  1,   /* field[1] = avatar */
  3,   /* field[3] = description */
  2,   /* field[2] = disappearingMessagesDuration */
  0,   /* field[0] = title */
};
static const ProtobufCIntRange group_attribute_blob__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor group_attribute_blob__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupAttributeBlob",
  "GroupAttributeBlob",
  "GroupAttributeBlob",
  "",
  sizeof(GroupAttributeBlob),
  4,
  group_attribute_blob__field_descriptors,
  group_attribute_blob__field_indices_by_name,
  1,  group_attribute_blob__number_ranges,
  (ProtobufCMessageInit) group_attribute_blob__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_invite_link__group_invite_link_contents_v1__field_descriptors[2] =
{
  {
    "groupMasterKey",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupInviteLink__GroupInviteLinkContentsV1, groupmasterkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inviteLinkPassword",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupInviteLink__GroupInviteLinkContentsV1, invitelinkpassword),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_invite_link__group_invite_link_contents_v1__field_indices_by_name[] = {
  0,   /* field[0] = groupMasterKey */
  1,   /* field[1] = inviteLinkPassword */
};
static const ProtobufCIntRange group_invite_link__group_invite_link_contents_v1__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor group_invite_link__group_invite_link_contents_v1__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupInviteLink.GroupInviteLinkContentsV1",
  "GroupInviteLinkContentsV1",
  "GroupInviteLink__GroupInviteLinkContentsV1",
  "",
  sizeof(GroupInviteLink__GroupInviteLinkContentsV1),
  2,
  group_invite_link__group_invite_link_contents_v1__field_descriptors,
  group_invite_link__group_invite_link_contents_v1__field_indices_by_name,
  1,  group_invite_link__group_invite_link_contents_v1__number_ranges,
  (ProtobufCMessageInit) group_invite_link__group_invite_link_contents_v1__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_invite_link__group_invite_link_contents_v10__field_descriptors[3] =
{
  {
    "groupMasterKey",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupInviteLink__GroupInviteLinkContentsV10, groupmasterkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inviteLinkPassword",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupInviteLink__GroupInviteLinkContentsV10, invitelinkpassword),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GroupInviteLink__GroupInviteLinkContentsV10, fid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_invite_link__group_invite_link_contents_v10__field_indices_by_name[] = {
  2,   /* field[2] = fid */
  0,   /* field[0] = groupMasterKey */
  1,   /* field[1] = inviteLinkPassword */
};
static const ProtobufCIntRange group_invite_link__group_invite_link_contents_v10__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor group_invite_link__group_invite_link_contents_v10__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupInviteLink.GroupInviteLinkContentsV10",
  "GroupInviteLinkContentsV10",
  "GroupInviteLink__GroupInviteLinkContentsV10",
  "",
  sizeof(GroupInviteLink__GroupInviteLinkContentsV10),
  3,
  group_invite_link__group_invite_link_contents_v10__field_descriptors,
  group_invite_link__group_invite_link_contents_v10__field_indices_by_name,
  1,  group_invite_link__group_invite_link_contents_v10__number_ranges,
  (ProtobufCMessageInit) group_invite_link__group_invite_link_contents_v10__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_invite_link__field_descriptors[2] =
{
  {
    "v1Contents",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupInviteLink, contents_case),
    offsetof(GroupInviteLink, v1contents),
    &group_invite_link__group_invite_link_contents_v1__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v10Contents",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GroupInviteLink, contents_case),
    offsetof(GroupInviteLink, v10contents),
    &group_invite_link__group_invite_link_contents_v10__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_invite_link__field_indices_by_name[] = {
  1,   /* field[1] = v10Contents */
  0,   /* field[0] = v1Contents */
};
static const ProtobufCIntRange group_invite_link__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor group_invite_link__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupInviteLink",
  "GroupInviteLink",
  "GroupInviteLink",
  "",
  sizeof(GroupInviteLink),
  2,
  group_invite_link__field_descriptors,
  group_invite_link__field_indices_by_name,
  2,  group_invite_link__number_ranges,
  (ProtobufCMessageInit) group_invite_link__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_join_info__field_descriptors[8] =
{
  {
    "publicKey",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupJoinInfo, publickey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "title",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupJoinInfo, title),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avatar",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GroupJoinInfo, avatar),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memberCount",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GroupJoinInfo, membercount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addFromInviteLink",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GroupJoinInfo, addfrominvitelink),
    &access_control__access_required__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "revision",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GroupJoinInfo, revision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pendingAdminApproval",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GroupJoinInfo, pendingadminapproval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(GroupJoinInfo, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_join_info__field_indices_by_name[] = {
  4,   /* field[4] = addFromInviteLink */
  2,   /* field[2] = avatar */
  7,   /* field[7] = description */
  3,   /* field[3] = memberCount */
  6,   /* field[6] = pendingAdminApproval */
  0,   /* field[0] = publicKey */
  5,   /* field[5] = revision */
  1,   /* field[1] = title */
};
static const ProtobufCIntRange group_join_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor group_join_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupJoinInfo",
  "GroupJoinInfo",
  "GroupJoinInfo",
  "",
  sizeof(GroupJoinInfo),
  8,
  group_join_info__field_descriptors,
  group_join_info__field_indices_by_name,
  1,  group_join_info__number_ranges,
  (ProtobufCMessageInit) group_join_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_external_credential__field_descriptors[1] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GroupExternalCredential, token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_external_credential__field_indices_by_name[] = {
  0,   /* field[0] = token */
};
static const ProtobufCIntRange group_external_credential__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor group_external_credential__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupExternalCredential",
  "GroupExternalCredential",
  "GroupExternalCredential",
  "",
  sizeof(GroupExternalCredential),
  1,
  group_external_credential__field_descriptors,
  group_external_credential__field_indices_by_name,
  1,  group_external_credential__number_ranges,
  (ProtobufCMessageInit) group_external_credential__init,
  NULL,NULL,NULL    /* reserved[123] */
};
