/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: UfsrvMessageQueue.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "UfsrvMessageQueue.pb-c.h"
void   session_message__geo_fence__init
                     (SessionMessage__GeoFence         *message)
{
  static const SessionMessage__GeoFence init_value = SESSION_MESSAGE__GEO_FENCE__INIT;
  *message = init_value;
}
void   session_message__init
                     (SessionMessage         *message)
{
  static const SessionMessage init_value = SESSION_MESSAGE__INIT;
  *message = init_value;
}
size_t session_message__get_packed_size
                     (const SessionMessage *message)
{
  assert(message->base.descriptor == &session_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t session_message__pack
                     (const SessionMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &session_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t session_message__pack_to_buffer
                     (const SessionMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &session_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SessionMessage *
       session_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SessionMessage *)
     protobuf_c_message_unpack (&session_message__descriptor,
                                allocator, len, data);
}
void   session_message__free_unpacked
                     (SessionMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &session_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message_queue_message__init
                     (MessageQueueMessage         *message)
{
  static const MessageQueueMessage init_value = MESSAGE_QUEUE_MESSAGE__INIT;
  *message = init_value;
}
size_t message_queue_message__get_packed_size
                     (const MessageQueueMessage *message)
{
  assert(message->base.descriptor == &message_queue_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_queue_message__pack
                     (const MessageQueueMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_queue_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_queue_message__pack_to_buffer
                     (const MessageQueueMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_queue_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageQueueMessage *
       message_queue_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageQueueMessage *)
     protobuf_c_message_unpack (&message_queue_message__descriptor,
                                allocator, len, data);
}
void   message_queue_message__free_unpacked
                     (MessageQueueMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_queue_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor session_message__geo_fence__field_descriptors[2] =
{
  {
    "geofence_current",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SessionMessage__GeoFence, has_geofence_current),
    offsetof(SessionMessage__GeoFence, geofence_current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geofence_past",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SessionMessage__GeoFence, has_geofence_past),
    offsetof(SessionMessage__GeoFence, geofence_past),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned session_message__geo_fence__field_indices_by_name[] = {
  0,   /* field[0] = geofence_current */
  1,   /* field[1] = geofence_past */
};
static const ProtobufCIntRange session_message__geo_fence__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor session_message__geo_fence__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SessionMessage.GeoFence",
  "GeoFence",
  "SessionMessage__GeoFence",
  "",
  sizeof(SessionMessage__GeoFence),
  2,
  session_message__geo_fence__field_descriptors,
  session_message__geo_fence__field_indices_by_name,
  1,  session_message__geo_fence__number_ranges,
  (ProtobufCMessageInit) session_message__geo_fence__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue session_message__status__enum_values_by_number[8] =
{
  { "QUIT", "SESSION_MESSAGE__STATUS__QUIT", 0 },
  { "CONNECTED", "SESSION_MESSAGE__STATUS__CONNECTED", 1 },
  { "SUSPENDED", "SESSION_MESSAGE__STATUS__SUSPENDED", 2 },
  { "INVALIDTED", "SESSION_MESSAGE__STATUS__INVALIDTED", 3 },
  { "HEARTBEAT", "SESSION_MESSAGE__STATUS__HEARTBEAT", 4 },
  { "PREFERENCE", "SESSION_MESSAGE__STATUS__PREFERENCE", 5 },
  { "GEOFENCED", "SESSION_MESSAGE__STATUS__GEOFENCED", 6 },
  { "REBOOTED", "SESSION_MESSAGE__STATUS__REBOOTED", 7 },
};
static const ProtobufCIntRange session_message__status__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex session_message__status__enum_values_by_name[8] =
{
  { "CONNECTED", 1 },
  { "GEOFENCED", 6 },
  { "HEARTBEAT", 4 },
  { "INVALIDTED", 3 },
  { "PREFERENCE", 5 },
  { "QUIT", 0 },
  { "REBOOTED", 7 },
  { "SUSPENDED", 2 },
};
const ProtobufCEnumDescriptor session_message__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SessionMessage.Status",
  "Status",
  "SessionMessage__Status",
  "",
  8,
  session_message__status__enum_values_by_number,
  8,
  session_message__status__enum_values_by_name,
  1,
  session_message__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor session_message__field_descriptors[9] =
{
  {
    "target_session",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(SessionMessage, target_session),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SessionMessage, status),
    &session_message__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fences",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SessionMessage, n_fences),
    offsetof(SessionMessage, fences),
    &fence_record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fences_invited",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SessionMessage, n_fences_invited),
    offsetof(SessionMessage, fences_invited),
    &fence_record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fences_blocked",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SessionMessage, n_fences_blocked),
    offsetof(SessionMessage, fences_blocked),
    &fence_record__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prefs",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SessionMessage, n_prefs),
    offsetof(SessionMessage, prefs),
    &user_preference__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fence_prefs",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SessionMessage, n_fence_prefs),
    offsetof(SessionMessage, fence_prefs),
    &fence_user_preference__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geo_fence",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SessionMessage, geo_fence),
    &session_message__geo_fence__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "header",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SessionMessage, header),
    &command_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned session_message__field_indices_by_name[] = {
  6,   /* field[6] = fence_prefs */
  2,   /* field[2] = fences */
  4,   /* field[4] = fences_blocked */
  3,   /* field[3] = fences_invited */
  7,   /* field[7] = geo_fence */
  8,   /* field[8] = header */
  5,   /* field[5] = prefs */
  1,   /* field[1] = status */
  0,   /* field[0] = target_session */
};
static const ProtobufCIntRange session_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor session_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SessionMessage",
  "SessionMessage",
  "SessionMessage",
  "",
  sizeof(SessionMessage),
  9,
  session_message__field_descriptors,
  session_message__field_indices_by_name,
  1,  session_message__number_ranges,
  (ProtobufCMessageInit) session_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message_queue_message__broadcast_semantics__enum_values_by_number[4] =
{
  { "INTER", "MESSAGE_QUEUE_MESSAGE__BROADCAST_SEMANTICS__INTER", 0 },
  { "INTRA", "MESSAGE_QUEUE_MESSAGE__BROADCAST_SEMANTICS__INTRA", 1 },
  { "INTRA_WITH_INTER_SEMANTICS", "MESSAGE_QUEUE_MESSAGE__BROADCAST_SEMANTICS__INTRA_WITH_INTER_SEMANTICS", 2 },
  { "INTER_WITH_INTRA_SEMANTICS", "MESSAGE_QUEUE_MESSAGE__BROADCAST_SEMANTICS__INTER_WITH_INTRA_SEMANTICS", 3 },
};
static const ProtobufCIntRange message_queue_message__broadcast_semantics__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex message_queue_message__broadcast_semantics__enum_values_by_name[4] =
{
  { "INTER", 0 },
  { "INTER_WITH_INTRA_SEMANTICS", 3 },
  { "INTRA", 1 },
  { "INTRA_WITH_INTER_SEMANTICS", 2 },
};
const ProtobufCEnumDescriptor message_queue_message__broadcast_semantics__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageQueueMessage.BroadcastSemantics",
  "BroadcastSemantics",
  "MessageQueueMessage__BroadcastSemantics",
  "",
  4,
  message_queue_message__broadcast_semantics__enum_values_by_number,
  4,
  message_queue_message__broadcast_semantics__enum_values_by_name,
  1,
  message_queue_message__broadcast_semantics__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor message_queue_message__field_descriptors[14] =
{
  {
    "origin",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MessageQueueMessage, origin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MessageQueueMessage, has_command_type),
    offsetof(MessageQueueMessage, command_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ufsrvuid",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(MessageQueueMessage, has_ufsrvuid),
    offsetof(MessageQueueMessage, ufsrvuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "storage_id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MessageQueueMessage, storage_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_ufsrv",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MessageQueueMessage, has_target_ufsrv),
    offsetof(MessageQueueMessage, target_ufsrv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wire_data",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MessageQueueMessage, wire_data),
    &data_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fence",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MessageQueueMessage, fence),
    &fence_command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MessageQueueMessage, message),
    &message_command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MessageQueueMessage, location),
    &location_command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MessageQueueMessage, session),
    &session_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "broadcast_semantics",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(MessageQueueMessage, has_broadcast_semantics),
    offsetof(MessageQueueMessage, broadcast_semantics),
    &message_queue_message__broadcast_semantics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ufsrv_req_id",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(MessageQueueMessage, has_ufsrv_req_id),
    offsetof(MessageQueueMessage, ufsrv_req_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geogroup_id",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MessageQueueMessage, has_geogroup_id),
    offsetof(MessageQueueMessage, geogroup_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MessageQueueMessage, user),
    &user_command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_queue_message__field_indices_by_name[] = {
  10,   /* field[10] = broadcast_semantics */
  1,   /* field[1] = command_type */
  6,   /* field[6] = fence */
  12,   /* field[12] = geogroup_id */
  8,   /* field[8] = location */
  7,   /* field[7] = message */
  0,   /* field[0] = origin */
  9,   /* field[9] = session */
  3,   /* field[3] = storage_id */
  4,   /* field[4] = target_ufsrv */
  11,   /* field[11] = ufsrv_req_id */
  2,   /* field[2] = ufsrvuid */
  13,   /* field[13] = user */
  5,   /* field[5] = wire_data */
};
static const ProtobufCIntRange message_queue_message__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 5, 2 },
  { 7, 3 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor message_queue_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MessageQueueMessage",
  "MessageQueueMessage",
  "MessageQueueMessage",
  "",
  sizeof(MessageQueueMessage),
  14,
  message_queue_message__field_descriptors,
  message_queue_message__field_indices_by_name,
  3,  message_queue_message__number_ranges,
  (ProtobufCMessageInit) message_queue_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
