/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: WebSocketMessage.proto */

#ifndef PROTOBUF_C_WebSocketMessage_2eproto__INCLUDED
#define PROTOBUF_C_WebSocketMessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _WebSocketRequestMessage WebSocketRequestMessage;
typedef struct _WebSocketResponseMessage WebSocketResponseMessage;
typedef struct _WebSocketMessage WebSocketMessage;


/* --- enums --- */

typedef enum _WebSocketMessage__Type {
  WEB_SOCKET_MESSAGE__TYPE__UNKNOWN = 0,
  WEB_SOCKET_MESSAGE__TYPE__REQUEST = 1,
  WEB_SOCKET_MESSAGE__TYPE__RESPONSE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(WEB_SOCKET_MESSAGE__TYPE)
} WebSocketMessage__Type;

/* --- messages --- */

struct  _WebSocketRequestMessage
{
  ProtobufCMessage base;
  char *verb;
  char *path;
  protobuf_c_boolean has_body;
  ProtobufCBinaryData body;
  protobuf_c_boolean has_id;
  uint64_t id;
};
#define WEB_SOCKET_REQUEST_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&web_socket_request_message__descriptor) \
    , NULL, NULL, 0, {0,NULL}, 0, 0 }


struct  _WebSocketResponseMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  uint64_t id;
  protobuf_c_boolean has_status;
  uint32_t status;
  char *message;
  protobuf_c_boolean has_body;
  ProtobufCBinaryData body;
};
#define WEB_SOCKET_RESPONSE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&web_socket_response_message__descriptor) \
    , 0, 0, 0, 0, NULL, 0, {0,NULL} }


struct  _WebSocketMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean has_type;
  WebSocketMessage__Type type;
  char *command;
  WebSocketRequestMessage *request;
  WebSocketResponseMessage *response;
  size_t n_headers;
  char **headers;
};
#define WEB_SOCKET_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&web_socket_message__descriptor) \
    , 0, WEB_SOCKET_MESSAGE__TYPE__UNKNOWN, NULL, NULL, NULL, 0,NULL }


/* WebSocketRequestMessage methods */
void   web_socket_request_message__init
                     (WebSocketRequestMessage         *message);
size_t web_socket_request_message__get_packed_size
                     (const WebSocketRequestMessage   *message);
size_t web_socket_request_message__pack
                     (const WebSocketRequestMessage   *message,
                      uint8_t             *out);
size_t web_socket_request_message__pack_to_buffer
                     (const WebSocketRequestMessage   *message,
                      ProtobufCBuffer     *buffer);
WebSocketRequestMessage *
       web_socket_request_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   web_socket_request_message__free_unpacked
                     (WebSocketRequestMessage *message,
                      ProtobufCAllocator *allocator);
/* WebSocketResponseMessage methods */
void   web_socket_response_message__init
                     (WebSocketResponseMessage         *message);
size_t web_socket_response_message__get_packed_size
                     (const WebSocketResponseMessage   *message);
size_t web_socket_response_message__pack
                     (const WebSocketResponseMessage   *message,
                      uint8_t             *out);
size_t web_socket_response_message__pack_to_buffer
                     (const WebSocketResponseMessage   *message,
                      ProtobufCBuffer     *buffer);
WebSocketResponseMessage *
       web_socket_response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   web_socket_response_message__free_unpacked
                     (WebSocketResponseMessage *message,
                      ProtobufCAllocator *allocator);
/* WebSocketMessage methods */
void   web_socket_message__init
                     (WebSocketMessage         *message);
size_t web_socket_message__get_packed_size
                     (const WebSocketMessage   *message);
size_t web_socket_message__pack
                     (const WebSocketMessage   *message,
                      uint8_t             *out);
size_t web_socket_message__pack_to_buffer
                     (const WebSocketMessage   *message,
                      ProtobufCBuffer     *buffer);
WebSocketMessage *
       web_socket_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   web_socket_message__free_unpacked
                     (WebSocketMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*WebSocketRequestMessage_Closure)
                 (const WebSocketRequestMessage *message,
                  void *closure_data);
typedef void (*WebSocketResponseMessage_Closure)
                 (const WebSocketResponseMessage *message,
                  void *closure_data);
typedef void (*WebSocketMessage_Closure)
                 (const WebSocketMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor web_socket_request_message__descriptor;
extern const ProtobufCMessageDescriptor web_socket_response_message__descriptor;
extern const ProtobufCMessageDescriptor web_socket_message__descriptor;
extern const ProtobufCEnumDescriptor    web_socket_message__type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_WebSocketMessage_2eproto__INCLUDED */
