/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: crypto_certificates.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "crypto_certificates.pb-c.h"
void   certificate__init
                     (Certificate         *message)
{
  static const Certificate init_value = CERTIFICATE__INIT;
  *message = init_value;
}
size_t certificate__get_packed_size
                     (const Certificate *message)
{
  assert(message->base.descriptor == &certificate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t certificate__pack
                     (const Certificate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &certificate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t certificate__pack_to_buffer
                     (const Certificate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &certificate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Certificate *
       certificate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Certificate *)
     protobuf_c_message_unpack (&certificate__descriptor,
                                allocator, len, data);
}
void   certificate__free_unpacked
                     (Certificate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &certificate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_certificate__init
                     (ServerCertificate         *message)
{
  static const ServerCertificate init_value = SERVER_CERTIFICATE__INIT;
  *message = init_value;
}
size_t server_certificate__get_packed_size
                     (const ServerCertificate *message)
{
  assert(message->base.descriptor == &server_certificate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_certificate__pack
                     (const ServerCertificate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_certificate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_certificate__pack_to_buffer
                     (const ServerCertificate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_certificate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerCertificate *
       server_certificate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerCertificate *)
     protobuf_c_message_unpack (&server_certificate__descriptor,
                                allocator, len, data);
}
void   server_certificate__free_unpacked
                     (ServerCertificate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_certificate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   identity_certificate__init
                     (IdentityCertificate         *message)
{
  static const IdentityCertificate init_value = IDENTITY_CERTIFICATE__INIT;
  *message = init_value;
}
size_t identity_certificate__get_packed_size
                     (const IdentityCertificate *message)
{
  assert(message->base.descriptor == &identity_certificate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t identity_certificate__pack
                     (const IdentityCertificate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &identity_certificate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t identity_certificate__pack_to_buffer
                     (const IdentityCertificate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &identity_certificate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IdentityCertificate *
       identity_certificate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IdentityCertificate *)
     protobuf_c_message_unpack (&identity_certificate__descriptor,
                                allocator, len, data);
}
void   identity_certificate__free_unpacked
                     (IdentityCertificate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &identity_certificate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sender_certificate__init
                     (SenderCertificate         *message)
{
  static const SenderCertificate init_value = SENDER_CERTIFICATE__INIT;
  *message = init_value;
}
size_t sender_certificate__get_packed_size
                     (const SenderCertificate *message)
{
  assert(message->base.descriptor == &sender_certificate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sender_certificate__pack
                     (const SenderCertificate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sender_certificate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sender_certificate__pack_to_buffer
                     (const SenderCertificate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sender_certificate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SenderCertificate *
       sender_certificate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SenderCertificate *)
     protobuf_c_message_unpack (&sender_certificate__descriptor,
                                allocator, len, data);
}
void   sender_certificate__free_unpacked
                     (SenderCertificate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sender_certificate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor certificate__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Certificate, has_id),
    offsetof(Certificate, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Certificate, has_key),
    offsetof(Certificate, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned certificate__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = key */
};
static const ProtobufCIntRange certificate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor certificate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Certificate",
  "Certificate",
  "Certificate",
  "",
  sizeof(Certificate),
  2,
  certificate__field_descriptors,
  certificate__field_indices_by_name,
  1,  certificate__number_ranges,
  (ProtobufCMessageInit) certificate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_certificate__field_descriptors[2] =
{
  {
    "certificate",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ServerCertificate, has_certificate),
    offsetof(ServerCertificate, certificate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ServerCertificate, has_signature),
    offsetof(ServerCertificate, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_certificate__field_indices_by_name[] = {
  0,   /* field[0] = certificate */
  1,   /* field[1] = signature */
};
static const ProtobufCIntRange server_certificate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor server_certificate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerCertificate",
  "ServerCertificate",
  "ServerCertificate",
  "",
  sizeof(ServerCertificate),
  2,
  server_certificate__field_descriptors,
  server_certificate__field_indices_by_name,
  1,  server_certificate__number_ranges,
  (ProtobufCMessageInit) server_certificate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor identity_certificate__field_descriptors[5] =
{
  {
    "sender",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IdentityCertificate, sender),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "senderDevice",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(IdentityCertificate, has_senderdevice),
    offsetof(IdentityCertificate, senderdevice),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expires",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(IdentityCertificate, has_expires),
    offsetof(IdentityCertificate, expires),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "identityKey",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(IdentityCertificate, has_identitykey),
    offsetof(IdentityCertificate, identitykey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signer",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(IdentityCertificate, signer),
    &server_certificate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned identity_certificate__field_indices_by_name[] = {
  2,   /* field[2] = expires */
  3,   /* field[3] = identityKey */
  0,   /* field[0] = sender */
  1,   /* field[1] = senderDevice */
  4,   /* field[4] = signer */
};
static const ProtobufCIntRange identity_certificate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor identity_certificate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IdentityCertificate",
  "IdentityCertificate",
  "IdentityCertificate",
  "",
  sizeof(IdentityCertificate),
  5,
  identity_certificate__field_descriptors,
  identity_certificate__field_indices_by_name,
  1,  identity_certificate__number_ranges,
  (ProtobufCMessageInit) identity_certificate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sender_certificate__field_descriptors[2] =
{
  {
    "certificate",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(SenderCertificate, has_certificate),
    offsetof(SenderCertificate, certificate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(SenderCertificate, has_signature),
    offsetof(SenderCertificate, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sender_certificate__field_indices_by_name[] = {
  0,   /* field[0] = certificate */
  1,   /* field[1] = signature */
};
static const ProtobufCIntRange sender_certificate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sender_certificate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SenderCertificate",
  "SenderCertificate",
  "SenderCertificate",
  "",
  sizeof(SenderCertificate),
  2,
  sender_certificate__field_descriptors,
  sender_certificate__field_indices_by_name,
  1,  sender_certificate__number_ranges,
  (ProtobufCMessageInit) sender_certificate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
