"<html>\n"
"<body>\n"
"\n"
"<script src=\"https://www.google.com/recaptcha/api.js\"></script>\n"
"\n"
"<div class=\"g-recaptcha\"\n"
"     data-sitekey=\"{{ google_captcha_site_key}}\"\n"
"     data-callback=\"onToken\"\n"
"     data-size=\"invisible\">\n"
"</div>\n"
"\n"
"<script>\n"
"\n"
"function onToken(token) {\n"
"  window.location = \"unfacdcaptcha://\" + token;\n"
"}\n"
"\n"
"window.onload = function(e) {\n"
"  grecaptcha.execute();\n"
"}\n"
"\n"
"</script>\n"
"\n"
"\n"
"</body>\n"
"</html>\n"
