"<!DOCTYPE html>"
"<html lang=\"en-US\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
"<title>unfacd successful registration verification</title>"
"</head>"
"<body>"
"<h2>Your unfacd registration verification is successful</h2><p>You are helping build the world&#39;s safest social and messaging network <span class=\"fr-emoticon fr-deletable fr-emoticon-img\" style=\"background: url(https://cdnjs.cloudflare.com/ajax/libs/emojione/2.0.1/assets/svg/1f615.svg);\">&nbsp;</span>&nbsp;</p><h3>What happens next</h3><p>Your device will automatically detect that your email was successfully verified. Head back to your device and confirm that it is displaying a 6-digit code number. If no code is displayed that means the detection timer has lapsed. Simply, tap on the &quot;RE-CHECK&quot; text to engage the automatic detection process. You are now ready for some optional profile information setting.</p><p><img src=\"http://unfacd.com/ufsrv/images/unfacd_rego_recheck_screen.png\" style=\"width: 300px;\" class=\"fr-fic fr-dib\"></p><h3>Profile screen</h3><p>After successful detection you&#39;ll be presented with an optional profile page, where you can set your nickname and avatar. You can skip this screen and do it later at any time.</p><h4>Lastly thanks for being cool and please be patient as we iron out bugs from unfacd <span class=\"fr-emoticon fr-deletable fr-emoticon-img\" style=\"background: url(https://cdnjs.cloudflare.com/ajax/libs/emojione/2.0.1/assets/svg/1f618.svg);\">&nbsp;</span>&nbsp;</h4>"
"</body>"
"</html>"