
/*
 * "keywords" is an array of the keywords which are the fixed syntactic
 * elements of the configuration file.  Each keyword has a string version
 * of the keyword and a token id, which should be an identifier which
 * matches that in a %token statement inside the parser.y file.
 */
/* tokens were generated by the following command
 awk '{print $2}' < keywords.h | awk 'BEGIN {FS="\}"; i=250;} $1 ~ "T_[A-Z]*" {printf("#define %s %d\n", $1, i++);}' > cctokens.h
*/

static struct keyword keywords[]={
 {"options", T_OPTIONS},
 {"redirection", T_REDIRECTION},
 {"redirection_type", T_REDIRECTION_TYPE},
 {"destination_host", T_DESTINATION_HOST},
 {"destination_port", T_DESTINATION_PORT},
 {"listen_on_port", T_LISTEN_ON_PORT}, 
 {"listen_on_ip", T_LISTEN_ON_IP}, 
 {"access_list", T_ACCESS_LIST},
 {"allow_all", T_ALLOW_ALL},
 {"deny_all", T_DENY_ALL},
 {"allow",    T_ALLOW},
 {"deny",     T_DENY}, 
 {"max_connections", T_MAX_CONNECTIONS},
 {"active", T_ACTIVE},
 {"passive", T_PASSIVE},
 {"intra_redirect_to", T_INTRA_REDIRECT_TO},
 {"redirection_id", T_REDIRECTION_ID},
 {"require_version", T_REQUIRE_VERSION},
 {(char *) NULL, 0}
};

